/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
    nodes: {
        cushion_GEO_stool_GEO_GRP: THREE.Mesh;
        stool_GEO_GRP_pedal_Bar_GEO: THREE.Mesh;
        stool_GEO_GRP_seatbar_Connector_GEO: THREE.Mesh;
        stool_GEO_GRP_pedal_Connector_GEO: THREE.Mesh;
        stool_GEO_GRP_pedal_GEO: THREE.Mesh;
        stool_GEO_GRP_seatbar_GEO: THREE.Mesh;
        stool_GEO_GRP_seat_Rim_GEO: THREE.Mesh;
        stool_GEO_GRP_base_GEO: THREE.Mesh;
        stool_GEO_GRP_footRest_GEO: THREE.Mesh;
        stool_GEO_GRP_bade_Connector_GEO: THREE.Mesh;
    };
    materials: {};
};

export function Stool({ ...props }: JSX.IntrinsicElements["group"]) {
    const group = useRef<THREE.Group>(null);
    const { nodes, materials } = useGLTF("/stool/stool.gltf") as GLTFResult;
    return (
        <group ref={group} {...props} dispose={null}>
            <mesh
                geometry={nodes.cushion_GEO_stool_GEO_GRP.geometry}
                material={nodes.cushion_GEO_stool_GEO_GRP.material}
            />
            <mesh
                geometry={nodes.stool_GEO_GRP_pedal_Bar_GEO.geometry}
                material={nodes.stool_GEO_GRP_pedal_Bar_GEO.material}
            />
            <mesh
                geometry={nodes.stool_GEO_GRP_seatbar_Connector_GEO.geometry}
                material={nodes.stool_GEO_GRP_seatbar_Connector_GEO.material}
            />
            <mesh
                geometry={nodes.stool_GEO_GRP_pedal_Connector_GEO.geometry}
                material={nodes.stool_GEO_GRP_pedal_Connector_GEO.material}
            />
            <mesh
                geometry={nodes.stool_GEO_GRP_pedal_GEO.geometry}
                material={nodes.stool_GEO_GRP_pedal_GEO.material}
            />
            <mesh
                geometry={nodes.stool_GEO_GRP_seatbar_GEO.geometry}
                material={nodes.stool_GEO_GRP_seatbar_GEO.material}
            />
            <mesh
                geometry={nodes.stool_GEO_GRP_seat_Rim_GEO.geometry}
                material={nodes.stool_GEO_GRP_seat_Rim_GEO.material}
            />
            <mesh
                geometry={nodes.stool_GEO_GRP_base_GEO.geometry}
                material={nodes.stool_GEO_GRP_base_GEO.material}
            />
            <mesh
                geometry={nodes.stool_GEO_GRP_footRest_GEO.geometry}
                material={nodes.stool_GEO_GRP_footRest_GEO.material}
            />
            <mesh
                geometry={nodes.stool_GEO_GRP_bade_Connector_GEO.geometry}
                material={nodes.stool_GEO_GRP_bade_Connector_GEO.material}
            />
        </group>
    );
}

useGLTF.preload("/stool/stool.gltf");
