/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: 碧 (https://sketchfab.com/LK_7)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/simple-street-light-127d854caca141bca50eb14f035d617b
title: Simple Street Light
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
    nodes: {
        StreetLight_Material003_0: THREE.Mesh;
        StreetLight_Material001_0: THREE.Mesh;
        StreetLight_Light_0: THREE.Mesh;
        StreetLight_Material004_0: THREE.Mesh;
        Plane_Material002_0: THREE.Mesh;
    };
    materials: {
        ["Material.003"]: THREE.MeshPhysicalMaterial;
        ["Material.001"]: THREE.MeshPhysicalMaterial;
        Light: THREE.MeshPhysicalMaterial;
        ["Material.004"]: THREE.MeshPhysicalMaterial;
        ["Material.002"]: THREE.MeshStandardMaterial;
    };
};

export function StreetLight({ ...props }: JSX.IntrinsicElements["group"]) {
    const group = useRef<THREE.Group>(null);
    const { nodes, materials } = useGLTF(
        "/simple_street_light/scene.gltf"
    ) as GLTFResult;
    return (
        <group ref={group} {...props} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
                <group rotation={[Math.PI / 2, 0, 0]}>
                    <group
                        position={[0.02, 176.35, -0.67]}
                        rotation={[0, -1.57, -1.57]}
                        scale={132.52}>
                        <mesh
                            geometry={nodes.StreetLight_Material003_0.geometry}
                            material={materials["Material.003"]}
                        />
                        <mesh
                            geometry={nodes.StreetLight_Material001_0.geometry}
                            material={materials["Material.001"]}
                        />
                        <mesh
                            geometry={nodes.StreetLight_Light_0.geometry}
                            material={materials.Light}
                        />
                        <mesh
                            geometry={nodes.StreetLight_Material004_0.geometry}
                            material={materials["Material.004"]}
                        />
                    </group>
                    <group rotation={[-Math.PI / 2, 0, 0]} scale={1000}>
                        <mesh
                            geometry={nodes.Plane_Material002_0.geometry}
                            material={materials["Material.002"]}
                        />
                    </group>
                </group>
            </group>
        </group>
    );
}

useGLTF.preload("/simple_street_light/scene.gltf");
