/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: MRowa (https://sketchfab.com/MRowa)
license: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
source: https://sketchfab.com/3d-models/roadsbridges-tileset-pack-558f2ea2ae7b4861b18eea228085674b
title: Roads&Bridges - Tileset pack
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    RoadForward_Placeable_0: THREE.Mesh;
    RoadEnd_Placeable_0: THREE.Mesh;
    RoadT_Placeable_0: THREE.Mesh;
    RoadX_Placeable_0: THREE.Mesh;
    RoadAngle_Placeable_0: THREE.Mesh;
    Road45_Placeable_0: THREE.Mesh;
    Road90_2x2_Placeable_0: THREE.Mesh;
    Road90_Placeable_0: THREE.Mesh;
    RoadForwardBridge_Placeable_0: THREE.Mesh;
    Road90Bridge_Placeable_0: THREE.Mesh;
    RoadXBridge_Placeable_0: THREE.Mesh;
    RoadEndBridge_Placeable_0: THREE.Mesh;
    RoadTBridge_Placeable_0: THREE.Mesh;
    RoadAngleBridge_Placeable_0: THREE.Mesh;
    Road45Bridge_Placeable_0: THREE.Mesh;
    Road90_2x2Bridge_Placeable_0: THREE.Mesh;
    RoadForwardUp_Placeable_0: THREE.Mesh;
    RoadUpBridge_Placeable_0: THREE.Mesh;
    BridgePillarEnd_Placeable_0: THREE.Mesh;
    BridgePillar_Placeable_0: THREE.Mesh;
    BridgePillarUp_Placeable_0: THREE.Mesh;
    Road90_2x2Up_Placeable_0: THREE.Mesh;
    Road90_2x2upBridge_Placeable_0: THREE.Mesh;
    BridgePillarEnd_2x2_Placeable_0: THREE.Mesh;
    BridgePillarSmall_Placeable_0: THREE.Mesh;
  };
  materials: {
    Placeable: THREE.MeshStandardMaterial;
  };
};

export default function Model({ ...props }: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials } = useGLTF("/roadtiles/scene.gltf") as GLTFResult;
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            position={[-20000, 0, -16000]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <group position={[80, -80, 0]}>
              <mesh
                geometry={nodes.RoadForward_Placeable_0.geometry}
                material={materials.Placeable}
              />
            </group>
            <group position={[120, -120, 0]}>
              <mesh
                geometry={nodes.RoadEnd_Placeable_0.geometry}
                material={materials.Placeable}
              />
            </group>
            <group position={[80, -160, 0]}>
              <mesh
                geometry={nodes.RoadT_Placeable_0.geometry}
                material={materials.Placeable}
              />
            </group>
            <group position={[160, -80, 0]}>
              <mesh
                geometry={nodes.RoadX_Placeable_0.geometry}
                material={materials.Placeable}
              />
            </group>
            <group position={[160, -160, 0]}>
              <mesh
                geometry={nodes.RoadAngle_Placeable_0.geometry}
                material={materials.Placeable}
              />
            </group>
            <group position={[140, -220, 0]}>
              <mesh
                geometry={nodes.Road45_Placeable_0.geometry}
                material={materials.Placeable}
              />
            </group>
            <group position={[280, -120, 0]}>
              <mesh
                geometry={nodes.Road90_2x2_Placeable_0.geometry}
                material={materials.Placeable}
              />
            </group>
            <group position={[100, -260, 0]}>
              <mesh
                geometry={nodes.Road90_Placeable_0.geometry}
                material={materials.Placeable}
              />
            </group>
            <group position={[120, -80, 0]}>
              <mesh
                geometry={nodes.RoadForwardBridge_Placeable_0.geometry}
                material={materials.Placeable}
              />
            </group>
            <group position={[140, -260, 0]}>
              <mesh
                geometry={nodes.Road90Bridge_Placeable_0.geometry}
                material={materials.Placeable}
              />
            </group>
            <group position={[200, -80, 0]}>
              <mesh
                geometry={nodes.RoadXBridge_Placeable_0.geometry}
                material={materials.Placeable}
              />
            </group>
            <group position={[160, -120, 0]}>
              <mesh
                geometry={nodes.RoadEndBridge_Placeable_0.geometry}
                material={materials.Placeable}
              />
            </group>
            <group position={[120, -160, 0]}>
              <mesh
                geometry={nodes.RoadTBridge_Placeable_0.geometry}
                material={materials.Placeable}
              />
            </group>
            <group position={[200, -160, 0]}>
              <mesh
                geometry={nodes.RoadAngleBridge_Placeable_0.geometry}
                material={materials.Placeable}
              />
            </group>
            <group position={[180, -220, 0]}>
              <mesh
                geometry={nodes.Road45Bridge_Placeable_0.geometry}
                material={materials.Placeable}
              />
            </group>
            <group position={[360, -120, 0]}>
              <mesh
                geometry={nodes.Road90_2x2Bridge_Placeable_0.geometry}
                material={materials.Placeable}
              />
            </group>
            <group position={[160, -240, 0]}>
              <mesh
                geometry={nodes.RoadForwardUp_Placeable_0.geometry}
                material={materials.Placeable}
              />
            </group>
            <group position={[200, -240, 0]}>
              <mesh
                geometry={nodes.RoadUpBridge_Placeable_0.geometry}
                material={materials.Placeable}
              />
            </group>
            <group position={[280, -240, 0]}>
              <mesh
                geometry={nodes.BridgePillarEnd_Placeable_0.geometry}
                material={materials.Placeable}
              />
            </group>
            <group position={[360, -240, 0]}>
              <mesh
                geometry={nodes.BridgePillar_Placeable_0.geometry}
                material={materials.Placeable}
              />
            </group>
            <group position={[240, -240, 0]}>
              <mesh
                geometry={nodes.BridgePillarUp_Placeable_0.geometry}
                material={materials.Placeable}
              />
            </group>
            <group position={[280, -200, 0]}>
              <mesh
                geometry={nodes.Road90_2x2Up_Placeable_0.geometry}
                material={materials.Placeable}
              />
            </group>
            <group position={[360, -200, 0]}>
              <mesh
                geometry={nodes.Road90_2x2upBridge_Placeable_0.geometry}
                material={materials.Placeable}
              />
            </group>
            <group position={[360, -200, 0]}>
              <mesh
                geometry={nodes.BridgePillarEnd_2x2_Placeable_0.geometry}
                material={materials.Placeable}
              />
            </group>
            <group position={[320, -240, 0]}>
              <mesh
                geometry={nodes.BridgePillarSmall_Placeable_0.geometry}
                material={materials.Placeable}
              />
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/roadtiles/scene.gltf");
