/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: SINNIK (https://sketchfab.com/sinnik)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/arcade-game-space-invaders-d3959de1a78747f58fb46915e111a265
title: Arcade Game - Space Invaders
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh;
    Object_3: THREE.Mesh;
    Object_4: THREE.Mesh;
    Object_5: THREE.Mesh;
  };
  materials: {
    CR_videogame_door: THREE.MeshStandardMaterial;
    CR_videogame_machine: THREE.MeshStandardMaterial;
    CR_videogamecoins: THREE.MeshStandardMaterial;
    CR_videogamedesign2: THREE.MeshStandardMaterial;
  };
};

export default function ArcadeSpaceInvaders({
  ...props
}: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials } = useGLTF(
    "/arcade_game_space_invaders/scene.gltf"
  ) as GLTFResult;
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials.CR_videogame_door}
        />
        <mesh
          geometry={nodes.Object_3.geometry}
          material={materials.CR_videogame_machine}
        />
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials.CR_videogamecoins}
        />
        <mesh
          geometry={nodes.Object_5.geometry}
          material={materials.CR_videogamedesign2}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/arcade_game_space_invaders/scene.gltf");
