/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    mesh_0: THREE.Mesh;
    mesh_0_1: THREE.Mesh;
    mesh_0_2: THREE.Mesh;
    mesh_0_3: THREE.Mesh;
    mesh_0_4: THREE.Mesh;
    mesh_0_5: THREE.Mesh;
    mesh_0_6: THREE.Mesh;
  };
  materials: {};
};

export default function GeneralStore({
  ...props
}: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials } = useGLTF(
    "/building_general_store/building_general_store.gltf"
  ) as GLTFResult;
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, 0, -0.01]}>
        <mesh
          geometry={nodes.mesh_0.geometry}
          material={nodes.mesh_0.material}
        />
        <mesh
          geometry={nodes.mesh_0_1.geometry}
          material={nodes.mesh_0_1.material}
        />
        <mesh
          geometry={nodes.mesh_0_2.geometry}
          material={nodes.mesh_0_2.material}
        />
        <mesh
          geometry={nodes.mesh_0_3.geometry}
          material={nodes.mesh_0_3.material}
        />
        <mesh
          geometry={nodes.mesh_0_4.geometry}
          material={nodes.mesh_0_4.material}
        />
        <mesh
          geometry={nodes.mesh_0_5.geometry}
          material={nodes.mesh_0_5.material}
        />
        <mesh
          geometry={nodes.mesh_0_6.geometry}
          material={nodes.mesh_0_6.material}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/building_general_store/building_general_store.gltf");
