/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    mesh_0: THREE.Mesh;
    mesh_1: THREE.Mesh;
    mesh_2: THREE.Mesh;
    mesh_3: THREE.Mesh;
    mesh_4: THREE.Mesh;
    mesh_5: THREE.Mesh;
    mesh_6: THREE.Mesh;
    mesh_7: THREE.Mesh;
    mesh_8: THREE.Mesh;
    mesh_9: THREE.Mesh;
    mesh_10: THREE.Mesh;
    mesh_11: THREE.Mesh;
    mesh_12: THREE.Mesh;
    mesh_13: THREE.Mesh;
    mesh_14: THREE.Mesh;
    mesh_15: THREE.Mesh;
    mesh_16: THREE.Mesh;
    mesh_17: THREE.Mesh;
    mesh_18: THREE.Mesh;
    mesh_19: THREE.Mesh;
    mesh_20: THREE.Mesh;
    mesh_21: THREE.Mesh;
    mesh_22: THREE.Mesh;
    mesh_23: THREE.Mesh;
    mesh_24: THREE.Mesh;
    mesh_25: THREE.Mesh;
    mesh_26: THREE.Mesh;
    mesh_27: THREE.Mesh;
    mesh_28: THREE.Mesh;
    mesh_29: THREE.Mesh;
    mesh_30: THREE.Mesh;
    mesh_31: THREE.Mesh;
    mesh_32: THREE.Mesh;
    mesh_33: THREE.Mesh;
    mesh_34: THREE.Mesh;
    mesh_35: THREE.Mesh;
    mesh_36: THREE.Mesh;
    mesh_37: THREE.Mesh;
    mesh_38: THREE.Mesh;
    mesh_39: THREE.Mesh;
    mesh_40: THREE.Mesh;
    mesh_41: THREE.Mesh;
    mesh_42: THREE.Mesh;
    mesh_43: THREE.Mesh;
    mesh_44: THREE.Mesh;
    mesh_45: THREE.Mesh;
    mesh_46: THREE.Mesh;
    mesh_47: THREE.Mesh;
    mesh_48: THREE.Mesh;
    mesh_49: THREE.Mesh;
    mesh_50: THREE.Mesh;
    mesh_51: THREE.Mesh;
    mesh_52: THREE.Mesh;
    mesh_53: THREE.Mesh;
    mesh_54: THREE.Mesh;
    mesh_55: THREE.Mesh;
    mesh_56: THREE.Mesh;
    mesh_57: THREE.Mesh;
    mesh_58: THREE.Mesh;
    mesh_59: THREE.Mesh;
    mesh_60: THREE.Mesh;
    mesh_61: THREE.Mesh;
    mesh_62: THREE.Mesh;
    mesh_63: THREE.Mesh;
    mesh_64: THREE.Mesh;
    mesh_65: THREE.Mesh;
    mesh_66: THREE.Mesh;
    mesh_67: THREE.Mesh;
    mesh_68: THREE.Mesh;
    mesh_69: THREE.Mesh;
    mesh_70: THREE.Mesh;
    mesh_71: THREE.Mesh;
    mesh_72: THREE.Mesh;
    mesh_73: THREE.Mesh;
    mesh_74: THREE.Mesh;
    mesh_75: THREE.Mesh;
    mesh_76: THREE.Mesh;
    mesh_77: THREE.Mesh;
    mesh_78: THREE.Mesh;
    mesh_79: THREE.Mesh;
    mesh_80: THREE.Mesh;
    mesh_81: THREE.Mesh;
    mesh_82: THREE.Mesh;
    mesh_83: THREE.Mesh;
    mesh_84: THREE.Mesh;
    mesh_85: THREE.Mesh;
    mesh_86: THREE.Mesh;
    mesh_87: THREE.Mesh;
    mesh_88: THREE.Mesh;
    mesh_89: THREE.Mesh;
    mesh_90: THREE.Mesh;
    mesh_91: THREE.Mesh;
    mesh_92: THREE.Mesh;
    mesh_93: THREE.Mesh;
    mesh_94: THREE.Mesh;
  };
  materials: {};
};

export default function BuildingFlat({
  ...props
}: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials } = useGLTF(
    "/building_flat/Art_deco_facade.gltf"
  ) as GLTFResult;
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.mesh_0.geometry}
        material={nodes.mesh_0.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_1.geometry}
        material={nodes.mesh_1.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_2.geometry}
        material={nodes.mesh_2.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_3.geometry}
        material={nodes.mesh_3.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_4.geometry}
        material={nodes.mesh_4.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_5.geometry}
        material={nodes.mesh_5.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_6.geometry}
        material={nodes.mesh_6.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_7.geometry}
        material={nodes.mesh_7.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_8.geometry}
        material={nodes.mesh_8.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_9.geometry}
        material={nodes.mesh_9.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_10.geometry}
        material={nodes.mesh_10.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_11.geometry}
        material={nodes.mesh_11.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_12.geometry}
        material={nodes.mesh_12.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_13.geometry}
        material={nodes.mesh_13.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_14.geometry}
        material={nodes.mesh_14.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_15.geometry}
        material={nodes.mesh_15.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_16.geometry}
        material={nodes.mesh_16.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_17.geometry}
        material={nodes.mesh_17.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_18.geometry}
        material={nodes.mesh_18.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_19.geometry}
        material={nodes.mesh_19.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_20.geometry}
        material={nodes.mesh_20.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_21.geometry}
        material={nodes.mesh_21.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_22.geometry}
        material={nodes.mesh_22.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_23.geometry}
        material={nodes.mesh_23.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_24.geometry}
        material={nodes.mesh_24.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_25.geometry}
        material={nodes.mesh_25.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_26.geometry}
        material={nodes.mesh_26.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_27.geometry}
        material={nodes.mesh_27.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_28.geometry}
        material={nodes.mesh_28.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_29.geometry}
        material={nodes.mesh_29.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_30.geometry}
        material={nodes.mesh_30.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_31.geometry}
        material={nodes.mesh_31.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_32.geometry}
        material={nodes.mesh_32.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_33.geometry}
        material={nodes.mesh_33.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_34.geometry}
        material={nodes.mesh_34.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_35.geometry}
        material={nodes.mesh_35.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_36.geometry}
        material={nodes.mesh_36.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_37.geometry}
        material={nodes.mesh_37.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_38.geometry}
        material={nodes.mesh_38.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_39.geometry}
        material={nodes.mesh_39.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_40.geometry}
        material={nodes.mesh_40.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_41.geometry}
        material={nodes.mesh_41.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_42.geometry}
        material={nodes.mesh_42.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_43.geometry}
        material={nodes.mesh_43.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_44.geometry}
        material={nodes.mesh_44.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_45.geometry}
        material={nodes.mesh_45.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_46.geometry}
        material={nodes.mesh_46.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_47.geometry}
        material={nodes.mesh_47.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_48.geometry}
        material={nodes.mesh_48.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_49.geometry}
        material={nodes.mesh_49.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_50.geometry}
        material={nodes.mesh_50.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_51.geometry}
        material={nodes.mesh_51.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_52.geometry}
        material={nodes.mesh_52.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_53.geometry}
        material={nodes.mesh_53.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_54.geometry}
        material={nodes.mesh_54.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_55.geometry}
        material={nodes.mesh_55.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_56.geometry}
        material={nodes.mesh_56.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_57.geometry}
        material={nodes.mesh_57.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_58.geometry}
        material={nodes.mesh_58.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_59.geometry}
        material={nodes.mesh_59.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_60.geometry}
        material={nodes.mesh_60.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_61.geometry}
        material={nodes.mesh_61.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_62.geometry}
        material={nodes.mesh_62.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_63.geometry}
        material={nodes.mesh_63.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_64.geometry}
        material={nodes.mesh_64.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_65.geometry}
        material={nodes.mesh_65.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_66.geometry}
        material={nodes.mesh_66.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_67.geometry}
        material={nodes.mesh_67.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_68.geometry}
        material={nodes.mesh_68.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_69.geometry}
        material={nodes.mesh_69.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_70.geometry}
        material={nodes.mesh_70.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_71.geometry}
        material={nodes.mesh_71.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_72.geometry}
        material={nodes.mesh_72.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_73.geometry}
        material={nodes.mesh_73.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_74.geometry}
        material={nodes.mesh_74.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_75.geometry}
        material={nodes.mesh_75.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_76.geometry}
        material={nodes.mesh_76.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_77.geometry}
        material={nodes.mesh_77.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_78.geometry}
        material={nodes.mesh_78.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_79.geometry}
        material={nodes.mesh_79.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_80.geometry}
        material={nodes.mesh_80.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_81.geometry}
        material={nodes.mesh_81.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_82.geometry}
        material={nodes.mesh_82.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_83.geometry}
        material={nodes.mesh_83.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_84.geometry}
        material={nodes.mesh_84.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_85.geometry}
        material={nodes.mesh_85.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_86.geometry}
        material={nodes.mesh_86.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_87.geometry}
        material={nodes.mesh_87.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_88.geometry}
        material={nodes.mesh_88.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_89.geometry}
        material={nodes.mesh_89.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_90.geometry}
        material={nodes.mesh_90.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_91.geometry}
        material={nodes.mesh_91.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_92.geometry}
        material={nodes.mesh_92.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_93.geometry}
        material={nodes.mesh_93.material}
        position={[0, 0, -0.35]}
      />
      <mesh
        geometry={nodes.mesh_94.geometry}
        material={nodes.mesh_94.material}
        position={[0, 0, -0.35]}
      />
    </group>
  );
}

useGLTF.preload("/building_flat/Art_deco_facade.gltf");
