/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: negar (https://sketchfab.com/negar)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/burger-8bd6e8b9603e4168aa3e38d299f28595
title: burger
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    seeds_SeedsColor_0: THREE.Mesh;
    top_bun_1_BunColor_0: THREE.Mesh;
    Lettuce_LettuceColor_0: THREE.Mesh;
    tomato_TomatoColor_0: THREE.Mesh;
    Cheese_CheeseColor_0: THREE.Mesh;
    beef_MeatColor_0: THREE.Mesh;
    Bottom_bun_BunColor_0: THREE.Mesh;
    Bottom_bun_Mat013_0: THREE.Mesh;
  };
  materials: {
    SeedsColor: THREE.MeshStandardMaterial;
    BunColor: THREE.MeshStandardMaterial;
    LettuceColor: THREE.MeshStandardMaterial;
    TomatoColor: THREE.MeshStandardMaterial;
    CheeseColor: THREE.MeshStandardMaterial;
    MeatColor: THREE.MeshStandardMaterial;
    ["Mat.013"]: THREE.MeshStandardMaterial;
  };
};

export default function Burger({ ...props }: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials } = useGLTF("/burger/scene.gltf") as GLTFResult;
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-0.18, 65.2, -0.27]}>
            <group position={[0, 22.97, 0]}>
              <group
                position={[-25.75, -15.1, -23.76]}
                rotation={[1.29, 0.27, -0.75]}
              >
                <mesh
                  geometry={nodes.seeds_SeedsColor_0.geometry}
                  material={materials.SeedsColor}
                />
              </group>
            </group>
            <group position={[0, -20.39, 0]}>
              <mesh
                geometry={nodes.top_bun_1_BunColor_0.geometry}
                material={materials.BunColor}
              />
            </group>
          </group>
          <group position={[-0.18, 30.7, -0.27]}>
            <mesh
              geometry={nodes.Lettuce_LettuceColor_0.geometry}
              material={materials.LettuceColor}
            />
          </group>
          <group position={[-0.18, 28.24, -0.27]}>
            <mesh
              geometry={nodes.tomato_TomatoColor_0.geometry}
              material={materials.TomatoColor}
            />
          </group>
          <group
            position={[0.29, 23.3, 0.08]}
            rotation={[-Math.PI, -0.71, -Math.PI]}
          >
            <mesh
              geometry={nodes.Cheese_CheeseColor_0.geometry}
              material={materials.CheeseColor}
            />
          </group>
          <group position={[-0.18, 9.24, -0.27]}>
            <mesh
              geometry={nodes.beef_MeatColor_0.geometry}
              material={materials.MeatColor}
            />
          </group>
          <group
            position={[-0.18, -9.42, -0.27]}
            rotation={[-Math.PI, -0.71, -Math.PI]}
          >
            <mesh
              geometry={nodes.Bottom_bun_BunColor_0.geometry}
              material={materials.BunColor}
            />
            <mesh
              geometry={nodes.Bottom_bun_Mat013_0.geometry}
              material={materials["Mat.013"]}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/burger/scene.gltf");
