/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: ChopperManiac (https://sketchfab.com/ChopperManiac)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/coffee-shop-isometric-051e5ab8bd934bcc995bb3366b47c4d8
title: Coffee Shop Isometric
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
    nodes: {
        Object_4: THREE.Mesh;
        Object_5: THREE.Mesh;
        Object_6: THREE.Mesh;
        Object_8: THREE.Mesh;
        Object_9: THREE.Mesh;
        Object_11: THREE.Mesh;
        Object_13: THREE.Mesh;
        Object_15: THREE.Mesh;
        Object_16: THREE.Mesh;
        Object_18: THREE.Mesh;
        Object_19: THREE.Mesh;
        Object_21: THREE.Mesh;
        Object_22: THREE.Mesh;
        Object_24: THREE.Mesh;
        Object_26: THREE.Mesh;
        Object_28: THREE.Mesh;
        Object_30: THREE.Mesh;
        Object_32: THREE.Mesh;
        Object_34: THREE.Mesh;
        Object_36: THREE.Mesh;
        Object_38: THREE.Mesh;
        Object_40: THREE.Mesh;
        Object_42: THREE.Mesh;
        Object_44: THREE.Mesh;
        Object_45: THREE.Mesh;
        Object_47: THREE.Mesh;
        Object_49: THREE.Mesh;
        Object_51: THREE.Mesh;
        Object_53: THREE.Mesh;
        Object_55: THREE.Mesh;
        Object_57: THREE.Mesh;
        Object_61: THREE.Mesh;
        Object_63: THREE.Mesh;
        Object_65: THREE.Mesh;
        Object_59: THREE.Mesh;
        Object_69: THREE.Mesh;
        Object_71: THREE.Mesh;
        Object_73: THREE.Mesh;
        Object_67: THREE.Mesh;
        Object_77: THREE.Mesh;
        Object_79: THREE.Mesh;
        Object_81: THREE.Mesh;
        Object_75: THREE.Mesh;
        Object_85: THREE.Mesh;
        Object_87: THREE.Mesh;
        Object_89: THREE.Mesh;
        Object_83: THREE.Mesh;
        Object_91: THREE.Mesh;
        Object_96: THREE.Mesh;
        Object_98: THREE.Mesh;
        Object_100: THREE.Mesh;
        Object_93: THREE.Mesh;
        Object_94: THREE.Mesh;
        Object_105: THREE.Mesh;
        Object_107: THREE.Mesh;
        Object_109: THREE.Mesh;
        Object_102: THREE.Mesh;
        Object_103: THREE.Mesh;
        Object_111: THREE.Mesh;
        Object_113: THREE.Mesh;
        Object_115: THREE.Mesh;
        Object_117: THREE.Mesh;
        Object_119: THREE.Mesh;
        Object_121: THREE.Mesh;
        Object_123: THREE.Mesh;
        Object_124: THREE.Mesh;
        Object_126: THREE.Mesh;
        Object_128: THREE.Mesh;
        Object_130: THREE.Mesh;
        Object_132: THREE.Mesh;
        Object_134: THREE.Mesh;
        Object_136: THREE.Mesh;
        Object_138: THREE.Mesh;
        Object_140: THREE.Mesh;
        Object_142: THREE.Mesh;
        Object_144: THREE.Mesh;
        Object_146: THREE.Mesh;
        Object_148: THREE.Mesh;
        Object_150: THREE.Mesh;
    };
    materials: {
        Casa: THREE.MeshStandardMaterial;
        Coffeshop: THREE.MeshStandardMaterial;
        Techo: THREE.MeshStandardMaterial;
        Piso: THREE.MeshStandardMaterial;
        Piso_fondo: THREE.MeshStandardMaterial;
        Espejos: THREE.MeshStandardMaterial;
        Cortinas: THREE.MeshStandardMaterial;
        Aire: THREE.MeshStandardMaterial;
        Salida_aire: THREE.MeshStandardMaterial;
        Mesas_sillas: THREE.MeshStandardMaterial;
        Manijas: THREE.MeshStandardMaterial;
        Tierra: THREE.MeshStandardMaterial;
        Tallo: THREE.MeshStandardMaterial;
        Arbolito: THREE.MeshStandardMaterial;
        Maseta: THREE.MeshStandardMaterial;
        Alfombra: THREE.MeshStandardMaterial;
        Lampara: THREE.MeshStandardMaterial;
        Lampara_2: THREE.MeshStandardMaterial;
        Letras: THREE.MeshStandardMaterial;
        Vaso: THREE.MeshStandardMaterial;
        Mantel: THREE.MeshStandardMaterial;
        Piso_Fondo: THREE.MeshStandardMaterial;
        Aire_Acondicionado: THREE.MeshStandardMaterial;
        ["Aire_Acondicionado.001"]: THREE.MeshStandardMaterial;
        Cable: THREE.MeshStandardMaterial;
        ["Luz_cartel.001"]: THREE.MeshStandardMaterial;
        Luz_cartel: THREE.MeshStandardMaterial;
    };
};

export  function CoffeeShop({
    ...props
}: JSX.IntrinsicElements["group"]) {
    const group = useRef<THREE.Group>(null);
    const { nodes, materials } = useGLTF(
        "/coffee_shop_isometric/scene.gltf"
    ) as GLTFResult;
    return (
        <group ref={group} {...props} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
                <group rotation={[Math.PI / 2, 0, 0]}>
                    <group
                        position={[0.2, 0.84, -0.32]}
                        rotation={[0, -Math.PI / 2, 0]}>
                        <mesh
                            geometry={nodes.Object_4.geometry}
                            material={materials.Casa}
                        />
                        <mesh
                            geometry={nodes.Object_5.geometry}
                            material={materials.Coffeshop}
                        />
                        <mesh
                            geometry={nodes.Object_6.geometry}
                            material={materials.Techo}
                        />
                    </group>
                    <group
                        position={[0.2, 0.46, -0.32]}
                        rotation={[0, -Math.PI / 2, 0]}>
                        <mesh
                            geometry={nodes.Object_8.geometry}
                            material={materials.Piso}
                        />
                        <mesh
                            geometry={nodes.Object_9.geometry}
                            material={materials.Piso_fondo}
                        />
                    </group>
                    <group
                        position={[0.72, 1.05, -0.03]}
                        rotation={[0, -Math.PI / 2, 0]}>
                        <mesh
                            geometry={nodes.Object_11.geometry}
                            material={materials.Casa}
                        />
                    </group>
                    <group
                        position={[0.2, 0.84, -0.32]}
                        rotation={[0, -Math.PI / 2, 0]}>
                        <mesh
                            geometry={nodes.Object_13.geometry}
                            material={materials.Casa}
                        />
                    </group>
                    <group
                        position={[0.2, 0.84, -0.32]}
                        rotation={[0, -Math.PI / 2, 0]}>
                        <mesh
                            geometry={nodes.Object_15.geometry}
                            material={materials.Espejos}
                        />
                        <mesh
                            geometry={nodes.Object_16.geometry}
                            material={materials.Casa}
                        />
                    </group>
                    <group
                        position={[0.2, 0.84, -0.32]}
                        rotation={[0, -Math.PI / 2, 0]}>
                        <mesh
                            geometry={nodes.Object_18.geometry}
                            material={materials.Espejos}
                        />
                        <mesh
                            geometry={nodes.Object_19.geometry}
                            material={materials.Casa}
                        />
                    </group>
                    <group
                        position={[0.72, 1.05, -0.03]}
                        rotation={[0, -Math.PI / 2, 0]}>
                        <mesh
                            geometry={nodes.Object_21.geometry}
                            material={materials.Espejos}
                        />
                        <mesh
                            geometry={nodes.Object_22.geometry}
                            material={materials.Casa}
                        />
                    </group>
                    <group position={[-0.32, 1.94, 1.06]}>
                        <mesh
                            geometry={nodes.Object_24.geometry}
                            material={materials.Cortinas}
                        />
                    </group>
                    <group
                        position={[1.55, 1.84, -1.5]}
                        rotation={[0, Math.PI / 2, 0]}>
                        <mesh
                            geometry={nodes.Object_26.geometry}
                            material={materials.Cortinas}
                        />
                    </group>
                    <group position={[-1.34, 2.83, -1.87]} scale={0.35}>
                        <mesh
                            geometry={nodes.Object_28.geometry}
                            material={materials.Aire}
                        />
                    </group>
                    <group position={[-1.4, 2.53, -0.26]} scale={0.05}>
                        <mesh
                            geometry={nodes.Object_30.geometry}
                            material={materials.Salida_aire}
                        />
                    </group>
                    <group position={[-0.55, 0.61, 1.49]}>
                        <mesh
                            geometry={nodes.Object_32.geometry}
                            material={materials.Mesas_sillas}
                        />
                    </group>
                    <group position={[-1.04, 0.65, 1.52]} scale={0.1}>
                        <mesh
                            geometry={nodes.Object_34.geometry}
                            material={materials.Mesas_sillas}
                        />
                    </group>
                    <group
                        position={[-0.62, 0.65, 0.95]}
                        rotation={[0, -Math.PI / 2, 0]}
                        scale={0.1}>
                        <mesh
                            geometry={nodes.Object_36.geometry}
                            material={materials.Mesas_sillas}
                        />
                    </group>
                    <group position={[1.89, 0.61, 1.49]}>
                        <mesh
                            geometry={nodes.Object_38.geometry}
                            material={materials.Mesas_sillas}
                        />
                    </group>
                    <group
                        position={[1.4, 0.65, 1.64]}
                        rotation={[0, 0.24, 0]}
                        scale={0.1}>
                        <mesh
                            geometry={nodes.Object_40.geometry}
                            material={materials.Mesas_sillas}
                        />
                    </group>
                    <group
                        position={[0.72, 1.05, -0.03]}
                        rotation={[0, -Math.PI / 2, 0]}>
                        <mesh
                            geometry={nodes.Object_42.geometry}
                            material={materials.Casa}
                        />
                    </group>
                    <group
                        position={[0.72, 1.05, -0.03]}
                        rotation={[0, -Math.PI / 2, 0]}>
                        <mesh
                            geometry={nodes.Object_44.geometry}
                            material={materials.Espejos}
                        />
                        <mesh
                            geometry={nodes.Object_45.geometry}
                            material={materials.Casa}
                        />
                    </group>
                    <group position={[0.74, 1.08, -0.03]} scale={0.01}>
                        <mesh
                            geometry={nodes.Object_47.geometry}
                            material={materials.Manijas}
                        />
                    </group>
                    <group
                        position={[0.71, 1.08, -0.03]}
                        rotation={[0, 0, Math.PI]}
                        scale={0.01}>
                        <mesh
                            geometry={nodes.Object_49.geometry}
                            material={materials.Manijas}
                        />
                    </group>
                    <group
                        position={[2.39, 0.61, -0.34]}
                        rotation={[0, Math.PI / 2, 0]}>
                        <mesh
                            geometry={nodes.Object_51.geometry}
                            material={materials.Mesas_sillas}
                        />
                    </group>
                    <group
                        position={[2.41, 0.65, 0.15]}
                        rotation={[0, Math.PI / 2, 0]}
                        scale={0.1}>
                        <mesh
                            geometry={nodes.Object_53.geometry}
                            material={materials.Mesas_sillas}
                        />
                    </group>
                    <group
                        position={[2.24, 0.65, -0.85]}
                        rotation={[0, -1.23, 0]}
                        scale={0.1}>
                        <mesh
                            geometry={nodes.Object_55.geometry}
                            material={materials.Mesas_sillas}
                        />
                    </group>
                    <group
                        position={[1.91, 0.65, 1.05]}
                        rotation={[0, -1.14, 0]}
                        scale={0.1}>
                        <mesh
                            geometry={nodes.Object_57.geometry}
                            material={materials.Mesas_sillas}
                        />
                    </group>
                    <group position={[1.3, 0.67, 0.3]} scale={0.19}>
                        <mesh
                            geometry={nodes.Object_61.geometry}
                            material={materials.Tierra}
                        />
                        <group position={[-0.01, -0.03, 0.01]} scale={0.17}>
                            <mesh
                                geometry={nodes.Object_63.geometry}
                                material={materials.Tallo}
                            />
                        </group>
                        <group position={[-0.02, 0.98, 0.02]} scale={5.15}>
                            <mesh
                                geometry={nodes.Object_65.geometry}
                                material={materials.Arbolito}
                            />
                        </group>
                        <mesh
                            geometry={nodes.Object_59.geometry}
                            material={materials.Maseta}
                        />
                    </group>
                    <group position={[-1.52, 0.67, 0.3]} scale={0.19}>
                        <mesh
                            geometry={nodes.Object_69.geometry}
                            material={materials.Tierra}
                        />
                        <group position={[-0.01, -0.03, 0.01]} scale={0.17}>
                            <mesh
                                geometry={nodes.Object_71.geometry}
                                material={materials.Tallo}
                            />
                        </group>
                        <group position={[-0.02, 0.98, 0.02]} scale={5.15}>
                            <mesh
                                geometry={nodes.Object_73.geometry}
                                material={materials.Arbolito}
                            />
                        </group>
                        <mesh
                            geometry={nodes.Object_67.geometry}
                            material={materials.Maseta}
                        />
                    </group>
                    <group position={[1.72, 0.67, -1.98]} scale={0.19}>
                        <mesh
                            geometry={nodes.Object_77.geometry}
                            material={materials.Tierra}
                        />
                        <group position={[-0.01, -0.03, 0.01]} scale={0.17}>
                            <mesh
                                geometry={nodes.Object_79.geometry}
                                material={materials.Tallo}
                            />
                        </group>
                        <group position={[-0.02, 0.98, 0.02]} scale={5.15}>
                            <mesh
                                geometry={nodes.Object_81.geometry}
                                material={materials.Arbolito}
                            />
                        </group>
                        <mesh
                            geometry={nodes.Object_75.geometry}
                            material={materials.Maseta}
                        />
                    </group>
                    <group position={[0.21, 0.67, 0.3]} scale={0.19}>
                        <mesh
                            geometry={nodes.Object_85.geometry}
                            material={materials.Tierra}
                        />
                        <group position={[-0.01, -0.03, 0.01]} scale={0.17}>
                            <mesh
                                geometry={nodes.Object_87.geometry}
                                material={materials.Tallo}
                            />
                        </group>
                        <group position={[-0.02, 0.98, 0.02]} scale={5.15}>
                            <mesh
                                geometry={nodes.Object_89.geometry}
                                material={materials.Arbolito}
                            />
                        </group>
                        <mesh
                            geometry={nodes.Object_83.geometry}
                            material={materials.Maseta}
                        />
                    </group>
                    <group position={[0.73, 0.58, 0.32]} scale={0.11}>
                        <mesh
                            geometry={nodes.Object_91.geometry}
                            material={materials.Alfombra}
                        />
                    </group>
                    <group
                        position={[-1.5, 0.54, 1.98]}
                        scale={[0.03, 0.07, 0.03]}>
                        <group
                            position={[0.03, 14.64, 0.03]}
                            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                            scale={[13.99, 30.07, 30.07]}>
                            <mesh
                                geometry={nodes.Object_96.geometry}
                                material={materials.Lampara}
                            />
                        </group>
                        <group
                            position={[5.46, 14.64, 0.03]}
                            scale={[2.41, 1.12, 2.41]}>
                            <mesh
                                geometry={nodes.Object_98.geometry}
                                material={materials.Lampara_2}
                            />
                        </group>
                        <group
                            position={[5.44, 14.64, 0.09]}
                            rotation={[-Math.PI, 0, 0]}
                            scale={[-2.28, 1.06, 2.28]}>
                            <mesh
                                geometry={nodes.Object_100.geometry}
                                material={materials.Letras}
                            />
                        </group>
                        <mesh
                            geometry={nodes.Object_93.geometry}
                            material={materials.Lampara}
                        />
                        <mesh
                            geometry={nodes.Object_94.geometry}
                            material={materials.Lampara_2}
                        />
                    </group>
                    <group
                        position={[2.51, 0.54, -1.86]}
                        rotation={[0, -Math.PI / 2, 0]}
                        scale={[0.03, 0.07, 0.03]}>
                        <group
                            position={[0.03, 14.64, 0.03]}
                            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                            scale={[13.99, 30.07, 30.07]}>
                            <mesh
                                geometry={nodes.Object_105.geometry}
                                material={materials.Lampara}
                            />
                        </group>
                        <group
                            position={[5.46, 14.64, 0.03]}
                            scale={[2.41, 1.12, 2.41]}>
                            <mesh
                                geometry={nodes.Object_107.geometry}
                                material={materials.Lampara_2}
                            />
                        </group>
                        <group
                            position={[5.44, 14.64, 0.09]}
                            rotation={[-Math.PI, 0, 0]}
                            scale={[-2.28, 1.06, 2.28]}>
                            <mesh
                                geometry={nodes.Object_109.geometry}
                                material={materials.Letras}
                            />
                        </group>
                        <mesh
                            geometry={nodes.Object_102.geometry}
                            material={materials.Lampara}
                        />
                        <mesh
                            geometry={nodes.Object_103.geometry}
                            material={materials.Lampara_2}
                        />
                    </group>
                    <group position={[1.74, 0.9, 1.66]} scale={0.16}>
                        <mesh
                            geometry={nodes.Object_111.geometry}
                            material={materials.Vaso}
                        />
                    </group>
                    <group position={[1.88, 0.9, 1.33]} scale={0.16}>
                        <mesh
                            geometry={nodes.Object_113.geometry}
                            material={materials.Vaso}
                        />
                    </group>
                    <group position={[1.82, 0.88, 1.47]} scale={0.45}>
                        <mesh
                            geometry={nodes.Object_115.geometry}
                            material={materials.Mantel}
                        />
                    </group>
                    <group
                        position={[2.36, 0.88, -0.27]}
                        rotation={[0, Math.PI / 2, 0]}
                        scale={0.45}>
                        <mesh
                            geometry={nodes.Object_117.geometry}
                            material={materials.Mantel}
                        />
                    </group>
                    <group position={[-0.61, 0.88, 1.47]} scale={0.45}>
                        <mesh
                            geometry={nodes.Object_119.geometry}
                            material={materials.Mantel}
                        />
                    </group>
                    <group position={[0, 0.16, 0]} scale={11.71}>
                        <mesh
                            geometry={nodes.Object_121.geometry}
                            material={materials.Piso_Fondo}
                        />
                    </group>
                    <group
                        position={[0.22, 2.98, -0.95]}
                        rotation={[0, Math.PI / 2, 0]}
                        scale={[0.18, 0.46, 0.18]}>
                        <mesh
                            geometry={nodes.Object_123.geometry}
                            material={materials.Aire_Acondicionado}
                        />
                        <mesh
                            geometry={nodes.Object_124.geometry}
                            material={materials["Aire_Acondicionado.001"]}
                        />
                    </group>
                    <group position={[-1.4, 2.53, -0.41]} scale={0.05}>
                        <mesh
                            geometry={nodes.Object_126.geometry}
                            material={materials.Salida_aire}
                        />
                    </group>
                    <group position={[2.32, 0.9, -0.52]} scale={0.16}>
                        <mesh
                            geometry={nodes.Object_128.geometry}
                            material={materials.Vaso}
                        />
                    </group>
                    <group
                        position={[1.48, 2.42, -2.1]}
                        rotation={[0, 0, -Math.PI / 2]}
                        scale={0.03}>
                        <mesh
                            geometry={nodes.Object_130.geometry}
                            material={materials["Aire_Acondicionado.001"]}
                        />
                    </group>
                    <group position={[1.94, 2.3, -2.11]} scale={0.17}>
                        <mesh
                            geometry={nodes.Object_132.geometry}
                            material={materials["Aire_Acondicionado.001"]}
                        />
                    </group>
                    <group
                        position={[0.34, 2.3, 0.07]}
                        rotation={[Math.PI / 2, 0, 0]}>
                        <mesh
                            geometry={nodes.Object_134.geometry}
                            material={materials.Letras}
                        />
                    </group>
                    <group position={[-0.84, 2.48, -0.35]}>
                        <mesh
                            geometry={nodes.Object_136.geometry}
                            material={materials.Cable}
                        />
                    </group>
                    <group position={[-0.84, 2.48, -0.48]}>
                        <mesh
                            geometry={nodes.Object_138.geometry}
                            material={materials.Cable}
                        />
                    </group>
                    <group position={[-0.84, 2.48, -1.77]}>
                        <mesh
                            geometry={nodes.Object_140.geometry}
                            material={materials.Cable}
                        />
                    </group>
                    <group
                        position={[1.95, 2.49, -2.09]}
                        rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
                        <mesh
                            geometry={nodes.Object_142.geometry}
                            material={materials["Luz_cartel.001"]}
                        />
                    </group>
                    <group
                        position={[1.98, 2.52, -2.09]}
                        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                        scale={0.72}>
                        <mesh
                            geometry={nodes.Object_144.geometry}
                            material={materials.Luz_cartel}
                        />
                    </group>
                    <group
                        position={[2.05, 2.65, -2.09]}
                        rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
                        <mesh
                            geometry={nodes.Object_146.geometry}
                            material={materials["Luz_cartel.001"]}
                        />
                    </group>
                    <group
                        position={[2.1, 2.65, -2.09]}
                        rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
                        <mesh
                            geometry={nodes.Object_148.geometry}
                            material={materials["Luz_cartel.001"]}
                        />
                    </group>
                    <group
                        position={[2.14, 2.51, -2.09]}
                        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                        scale={0.72}>
                        <mesh
                            geometry={nodes.Object_150.geometry}
                            material={materials["Luz_cartel.001"]}
                        />
                    </group>
                </group>
            </group>
        </group>
    );
}

useGLTF.preload("/coffee_shop_isometric/scene.gltf");
