/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Daniyal Malik (https://sketchfab.com/daniyalmalik)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/scifi-building-1-0ae51cf0fd21473a98a26207cbc932df
title: Scifi Building 1
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    polySurface19_Default_0: THREE.Mesh;
    polySurface6_Emm_0: THREE.Mesh;
    polySurface6_Default_0: THREE.Mesh;
    polySurface48_Emm_0: THREE.Mesh;
    polySurface48_Default_0: THREE.Mesh;
    polySurface49_Emm_0: THREE.Mesh;
    polySurface49_Default_0: THREE.Mesh;
    polySurface50_Emm_0: THREE.Mesh;
    polySurface50_Default_0: THREE.Mesh;
    polySurface51_Emm_0: THREE.Mesh;
    polySurface51_Default_0: THREE.Mesh;
    polySurface52_Emm_0: THREE.Mesh;
    polySurface52_Default_0: THREE.Mesh;
    polySurface53_Emm_0: THREE.Mesh;
    polySurface53_Default_0: THREE.Mesh;
    polySurface54_Emm_0: THREE.Mesh;
    polySurface54_Default_0: THREE.Mesh;
    polySurface4_Default_0: THREE.Mesh;
    polySurface4_Emm_0: THREE.Mesh;
    polySurface20_conc_0: THREE.Mesh;
    polySurface22_conc_0: THREE.Mesh;
    polySurface24_conc_0: THREE.Mesh;
    polySurface26_conc_0: THREE.Mesh;
    polySurface28_conc_0: THREE.Mesh;
    polySurface30_conc_0: THREE.Mesh;
    polySurface32_conc_0: THREE.Mesh;
    polySurface34_conc_0: THREE.Mesh;
    polySurface36_conc_0: THREE.Mesh;
    polySurface38_conc_0: THREE.Mesh;
    polySurface40_conc_0: THREE.Mesh;
    polySurface42_conc_0: THREE.Mesh;
    polySurface44_conc_0: THREE.Mesh;
    polySurface46_conc_0: THREE.Mesh;
    polySurface47_conc_0: THREE.Mesh;
    pPlane1_Default_0: THREE.Mesh;
    pPlane2_Default_0: THREE.Mesh;
    pPlane3_Default_0: THREE.Mesh;
    pPlane4_Default_0: THREE.Mesh;
    pPlane5_Default_0: THREE.Mesh;
    pPlane6_Default_0: THREE.Mesh;
    pPlane7_Default_0: THREE.Mesh;
    pPlane15_Default_0: THREE.Mesh;
    pPlane16_Default_0: THREE.Mesh;
    pPlane17_Default_0: THREE.Mesh;
    pPlane18_Default_0: THREE.Mesh;
    pPlane19_Default_0: THREE.Mesh;
    pPlane20_Default_0: THREE.Mesh;
    pPlane21_Default_0: THREE.Mesh;
    pPlane27_Default_0: THREE.Mesh;
    pPlane28_Default_0: THREE.Mesh;
    pPlane29_Default_0: THREE.Mesh;
    pPlane30_Default_0: THREE.Mesh;
    pPlane32_Default_0: THREE.Mesh;
    pPlane33_Default_0: THREE.Mesh;
    pPlane34_Default_0: THREE.Mesh;
    pPlane35_conc_0: THREE.Mesh;
  };
  materials: {
    Default: THREE.MeshStandardMaterial;
    material: THREE.MeshStandardMaterial;
    conc: THREE.MeshStandardMaterial;
  };
};

export default function ScifiBuilding({
  ...props
}: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials } = useGLTF(
    "/scifi_building/scene.gltf"
  ) as GLTFResult;
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0.17, 3.42, -0.01]}>
            <mesh
              geometry={nodes.polySurface19_Default_0.geometry}
              material={materials.Default}
            />
            <mesh
              geometry={nodes.polySurface6_Emm_0.geometry}
              material={materials.material}
            />
            <mesh
              geometry={nodes.polySurface6_Default_0.geometry}
              material={materials.Default}
            />
            <group position={[0, -2.3, 0]}>
              <mesh
                geometry={nodes.polySurface48_Emm_0.geometry}
                material={materials.material}
              />
              <mesh
                geometry={nodes.polySurface48_Default_0.geometry}
                material={materials.Default}
              />
            </group>
            <group position={[0, -4.6, 0]}>
              <mesh
                geometry={nodes.polySurface49_Emm_0.geometry}
                material={materials.material}
              />
              <mesh
                geometry={nodes.polySurface49_Default_0.geometry}
                material={materials.Default}
              />
            </group>
            <group position={[0, -6.91, 0]}>
              <mesh
                geometry={nodes.polySurface50_Emm_0.geometry}
                material={materials.material}
              />
              <mesh
                geometry={nodes.polySurface50_Default_0.geometry}
                material={materials.Default}
              />
            </group>
            <group position={[0, -9.21, 0]}>
              <mesh
                geometry={nodes.polySurface51_Emm_0.geometry}
                material={materials.material}
              />
              <mesh
                geometry={nodes.polySurface51_Default_0.geometry}
                material={materials.Default}
              />
            </group>
            <group position={[0, -11.51, 0]}>
              <mesh
                geometry={nodes.polySurface52_Emm_0.geometry}
                material={materials.material}
              />
              <mesh
                geometry={nodes.polySurface52_Default_0.geometry}
                material={materials.Default}
              />
            </group>
            <group position={[0, -13.81, 0]}>
              <mesh
                geometry={nodes.polySurface53_Emm_0.geometry}
                material={materials.material}
              />
              <mesh
                geometry={nodes.polySurface53_Default_0.geometry}
                material={materials.Default}
              />
            </group>
            <group position={[0, -16.12, 0]}>
              <mesh
                geometry={nodes.polySurface54_Emm_0.geometry}
                material={materials.material}
              />
              <mesh
                geometry={nodes.polySurface54_Default_0.geometry}
                material={materials.Default}
              />
            </group>
            <mesh
              geometry={nodes.polySurface4_Default_0.geometry}
              material={materials.Default}
            />
            <mesh
              geometry={nodes.polySurface4_Emm_0.geometry}
              material={materials.material}
            />
            <mesh
              geometry={nodes.polySurface20_conc_0.geometry}
              material={materials.conc}
            />
            <mesh
              geometry={nodes.polySurface22_conc_0.geometry}
              material={materials.conc}
            />
            <mesh
              geometry={nodes.polySurface24_conc_0.geometry}
              material={materials.conc}
            />
            <mesh
              geometry={nodes.polySurface26_conc_0.geometry}
              material={materials.conc}
            />
            <mesh
              geometry={nodes.polySurface28_conc_0.geometry}
              material={materials.conc}
            />
            <mesh
              geometry={nodes.polySurface30_conc_0.geometry}
              material={materials.conc}
            />
            <mesh
              geometry={nodes.polySurface32_conc_0.geometry}
              material={materials.conc}
            />
            <mesh
              geometry={nodes.polySurface34_conc_0.geometry}
              material={materials.conc}
            />
            <mesh
              geometry={nodes.polySurface36_conc_0.geometry}
              material={materials.conc}
            />
            <mesh
              geometry={nodes.polySurface38_conc_0.geometry}
              material={materials.conc}
            />
            <mesh
              geometry={nodes.polySurface40_conc_0.geometry}
              material={materials.conc}
            />
            <mesh
              geometry={nodes.polySurface42_conc_0.geometry}
              material={materials.conc}
            />
            <mesh
              geometry={nodes.polySurface44_conc_0.geometry}
              material={materials.conc}
            />
            <mesh
              geometry={nodes.polySurface46_conc_0.geometry}
              material={materials.conc}
            />
            <mesh
              geometry={nodes.polySurface47_conc_0.geometry}
              material={materials.conc}
            />
          </group>
          <group
            position={[3.85, 22.88, -1.47]}
            rotation={[0, 0, -Math.PI / 2]}
          >
            <mesh
              geometry={nodes.pPlane1_Default_0.geometry}
              material={materials.Default}
            />
          </group>
          <group
            position={[3.85, 19.66, -1.47]}
            rotation={[0, 0, -Math.PI / 2]}
          >
            <mesh
              geometry={nodes.pPlane2_Default_0.geometry}
              material={materials.Default}
            />
          </group>
          <group
            position={[3.85, 16.43, -1.47]}
            rotation={[0, 0, -Math.PI / 2]}
          >
            <mesh
              geometry={nodes.pPlane3_Default_0.geometry}
              material={materials.Default}
            />
          </group>
          <group
            position={[3.85, 13.21, -1.47]}
            rotation={[0, 0, -Math.PI / 2]}
          >
            <mesh
              geometry={nodes.pPlane4_Default_0.geometry}
              material={materials.Default}
            />
          </group>
          <group position={[3.85, 9.98, -1.47]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh
              geometry={nodes.pPlane5_Default_0.geometry}
              material={materials.Default}
            />
          </group>
          <group position={[3.85, 6.76, -1.47]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh
              geometry={nodes.pPlane6_Default_0.geometry}
              material={materials.Default}
            />
          </group>
          <group position={[3.85, 3.53, -1.47]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh
              geometry={nodes.pPlane7_Default_0.geometry}
              material={materials.Default}
            />
          </group>
          <group
            position={[-2.53, 3.53, -3.66]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={[1, 1, 0.38]}
          >
            <mesh
              geometry={nodes.pPlane15_Default_0.geometry}
              material={materials.Default}
            />
          </group>
          <group
            position={[-2.53, 6.76, -3.66]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={[1, 1, 0.38]}
          >
            <mesh
              geometry={nodes.pPlane16_Default_0.geometry}
              material={materials.Default}
            />
          </group>
          <group
            position={[-2.53, 9.98, -3.66]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={[1, 1, 0.38]}
          >
            <mesh
              geometry={nodes.pPlane17_Default_0.geometry}
              material={materials.Default}
            />
          </group>
          <group
            position={[-2.53, 22.88, -3.66]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={[1, 1, 0.38]}
          >
            <mesh
              geometry={nodes.pPlane18_Default_0.geometry}
              material={materials.Default}
            />
          </group>
          <group
            position={[-2.53, 19.66, -3.66]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={[1, 1, 0.38]}
          >
            <mesh
              geometry={nodes.pPlane19_Default_0.geometry}
              material={materials.Default}
            />
          </group>
          <group
            position={[-2.53, 13.21, -3.66]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={[1, 1, 0.38]}
          >
            <mesh
              geometry={nodes.pPlane20_Default_0.geometry}
              material={materials.Default}
            />
          </group>
          <group
            position={[-2.53, 16.43, -3.66]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={[1, 1, 0.38]}
          >
            <mesh
              geometry={nodes.pPlane21_Default_0.geometry}
              material={materials.Default}
            />
          </group>
          <mesh
            geometry={nodes.pPlane27_Default_0.geometry}
            material={materials.Default}
          />
          <group
            position={[-1.43, 0, 0.45]}
            rotation={[0, -Math.PI / 4, 0]}
            scale={[1, 1, 1.03]}
          >
            <mesh
              geometry={nodes.pPlane28_Default_0.geometry}
              material={materials.Default}
            />
          </group>
          <group
            position={[3.12, 0, 0.22]}
            rotation={[0, Math.PI / 2, 0]}
            scale={[1, 1, 0.89]}
          >
            <mesh
              geometry={nodes.pPlane29_Default_0.geometry}
              material={materials.Default}
            />
          </group>
          <group
            position={[-0.26, 0, 0.22]}
            rotation={[0, Math.PI / 2, 0]}
            scale={[1, 1, 0.89]}
          >
            <mesh
              geometry={nodes.pPlane30_Default_0.geometry}
              material={materials.Default}
            />
          </group>
          <group
            position={[0.34, 0, -2.9]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={[1, 1, 0.89]}
          >
            <mesh
              geometry={nodes.pPlane32_Default_0.geometry}
              material={materials.Default}
            />
          </group>
          <group
            position={[0.34, 0, 0.47]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={[1, 1, 0.88]}
          >
            <mesh
              geometry={nodes.pPlane33_Default_0.geometry}
              material={materials.Default}
            />
          </group>
          <group
            position={[0.18, 0, 6.92]}
            rotation={[0, Math.PI / 2, 0]}
            scale={[1, 1, 1.01]}
          >
            <mesh
              geometry={nodes.pPlane34_Default_0.geometry}
              material={materials.Default}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/scifi_building/scene.gltf");
