/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: SCADL & Co (https://sketchfab.com/scadl)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/townhall-d8c5403ff1954eec8abc9e096b3376ee
title: TownHall
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
    nodes: {
        Object_4: THREE.Mesh;
        Object_5: THREE.Mesh;
        Object_6: THREE.Mesh;
        Object_7: THREE.Mesh;
        Object_8: THREE.Mesh;
        Object_10: THREE.Mesh;
        Object_12: THREE.Mesh;
    };
    materials: {
        RoofingClay: THREE.MeshStandardMaterial;
        FrontColor: THREE.MeshStandardMaterial;
        WindowLight: THREE.MeshStandardMaterial;
        Wooden: THREE.MeshStandardMaterial;
        Stena: THREE.MeshStandardMaterial;
        Ground: THREE.MeshStandardMaterial;
    };
};

export function Townhall({ ...props }: JSX.IntrinsicElements["group"]) {
    const group = useRef<THREE.Group>(null);
    const { nodes, materials } = useGLTF("/townhall/scene.gltf") as GLTFResult;
    return (
        <group ref={group} {...props} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
                <group rotation={[Math.PI / 2, 0, 0]}>
                    <group
                        position={[14.39, 15.09, -5.92]}
                        rotation={[Math.PI / 2, 0, 0]}>
                        <mesh
                            geometry={nodes.Object_4.geometry}
                            material={materials.RoofingClay}
                        />
                        <mesh
                            geometry={nodes.Object_5.geometry}
                            material={materials.FrontColor}
                        />
                        <mesh
                            geometry={nodes.Object_6.geometry}
                            material={materials.WindowLight}
                        />
                        <mesh
                            geometry={nodes.Object_7.geometry}
                            material={materials.Wooden}
                        />
                        <mesh
                            geometry={nodes.Object_8.geometry}
                            material={materials.Stena}
                        />
                    </group>
                    <group
                        position={[14.39, 15.09, -5.92]}
                        rotation={[Math.PI / 2, 0, 0]}>
                        <mesh
                            geometry={nodes.Object_10.geometry}
                            material={materials.FrontColor}
                        />
                    </group>
                    <mesh
                        geometry={nodes.Object_12.geometry}
                        material={materials.Ground}
                    />
                </group>
            </group>
        </group>
    );
}

useGLTF.preload("/townhall/scene.gltf");
