/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Maicon D. Curriel (https://sketchfab.com/maiconcurriel)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/camaro-ss-4c3a88f20a254c4aacf0a1834df2717b
title: Camaro SS
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { GLTF } from "three-stdlib";
type ActionName = "Take 001";
// type GLTFActions = Record<ActionName, THREE.AnimationAction>;

interface GLTFAction extends THREE.AnimationClip {
    name: ActionName;
}
type GLTFResult = GLTF & {
    nodes: {
        KIT00_LEFT_HEADLIGHT_OFF_A_misc_0: THREE.Mesh;
        KIT00_RIGHT_HEADLIGHT_OFF_A_misc_0: THREE.Mesh;
        BASE_A_color_0: THREE.Mesh;
        ["KIT00_BODY_A_Material_#523_0"]: THREE.Mesh;
        KIT00_BODY_A_color_0: THREE.Mesh;
        KIT00_BODY_A_alumm_0: THREE.Mesh;
        KIT00_BODY_A_black_0: THREE.Mesh;
        KIT00_BODY_A_misc_0: THREE.Mesh;
        KIT00_BODY_A_color2_0: THREE.Mesh;
        KIT00_DOORLINE_A_color2_0: THREE.Mesh;
        KIT00_DOOR_LEFT_A_color_0: THREE.Mesh;
        KIT00_DOOR_LEFT_A_alumm_0: THREE.Mesh;
        KIT00_DOOR_RIGHT_A_color_0: THREE.Mesh;
        KIT00_DOOR_RIGHT_A_alumm_0: THREE.Mesh;
        KIT00_EXHAUST_A_alumm_0: THREE.Mesh;
        KIT00_FRONT_BUMPER_A_color_0: THREE.Mesh;
        KIT00_FRONT_BUMPER_A_black_0: THREE.Mesh;
        KIT00_FRONT_BUMPER_A_glass_0: THREE.Mesh;
        KIT00_FRONT_BUMPER_A_alumm_0: THREE.Mesh;
        ["KIT00_FRONT_BUMPER_A_Material_#293_0"]: THREE.Mesh;
        KIT00_FRONT_BUMPER_A_misc_0: THREE.Mesh;
        ["KIT00_FRONT_BUMPER_BADGING_SET_A_Material_#523_0"]: THREE.Mesh;
        KIT00_FRONT_LEFT_WINDOW_A_windows_0: THREE.Mesh;
        KIT00_FRONT_RIGHT_WINDOW_A_windows_0: THREE.Mesh;
        KIT00_FRONT_TIRE_A_tire_0: THREE.Mesh;
        KIT00_FRONT_TIRE_A_rim_0: THREE.Mesh;
        KIT00_FRONT_WINDOW_A_windows_0: THREE.Mesh;
        KIT00_HOOD_A_color_0: THREE.Mesh;
        KIT00_HOOD_A_misc_0: THREE.Mesh;
        KIT00_INTERIOR_A_interior_0: THREE.Mesh;
        KIT00_INTERIOR_A_mirror_0: THREE.Mesh;
        KIT00_LEFT_BRAKELIGHT_A_break_0: THREE.Mesh;
        KIT00_LEFT_BRAKELIGHT_GLASS_A_breakglass_0: THREE.Mesh;
        KIT00_LEFT_HEADLIGHT_A_headlight_0: THREE.Mesh;
        KIT00_LEFT_HEADLIGHT_GLASS_A_headglass_0: THREE.Mesh;
        KIT00_LEFT_SIDE_MIRROR_A_alumm_0: THREE.Mesh;
        KIT00_LEFT_SIDE_MIRROR_A_mirror_0: THREE.Mesh;
        KIT00_REAR_BUMPER_A_glass_0: THREE.Mesh;
        KIT00_REAR_BUMPER_A_color_0: THREE.Mesh;
        KIT00_REAR_BUMPER_A_misc_0: THREE.Mesh;
        KIT00_REAR_BUMPER_A_black_0: THREE.Mesh;
        KIT00_REAR_BUMPER_A_alumm_0: THREE.Mesh;
        ["KIT00_REAR_BUMPER_BADGING_SET_A_Material_#523_0"]: THREE.Mesh;
        KIT00_REAR_BUMPER_BADGING_SET_A_alumm_0: THREE.Mesh;
        KIT00_REAR_BUMPER_BADGING_SET_A_misc_0: THREE.Mesh;
        KIT00_REAR_BUMPER_BADGING_SET_A_black_0: THREE.Mesh;
        KIT00_REAR_WINDOW_A_windows_0: THREE.Mesh;
        KIT00_RIGHT_BRAKELIGHT_A_break_0: THREE.Mesh;
        KIT00_RIGHT_BRAKELIGHT_GLASS_A_breakglass_0: THREE.Mesh;
        KIT00_RIGHT_HEADLIGHT_A_headlight_0: THREE.Mesh;
        KIT00_RIGHT_HEADLIGHT_GLASS_A_headglass_0: THREE.Mesh;
        KIT00_RIGHT_SIDE_MIRROR_A_alumm_0: THREE.Mesh;
        KIT00_RIGHT_SIDE_MIRROR_A_mirror_0: THREE.Mesh;
        KIT00_ROOF_A_color_0: THREE.Mesh;
        KIT00_ROOF_A_alumm_0: THREE.Mesh;
        ["KIT00_SKIRT_A_Material_#523_0"]: THREE.Mesh;
        KIT00_SKIRT_A_color2_0: THREE.Mesh;
        KIT00_SKIRT_A_black_0: THREE.Mesh;
        KIT00_SKIRT_A_color_0: THREE.Mesh;
        KIT00_SKIRT_A_alumm_0: THREE.Mesh;
        KIT00_SPOILER_A_color_0: THREE.Mesh;
        KIT00_FRONT_TIRE_A001_tire_0: THREE.Mesh;
        KIT00_FRONT_TIRE_A001_rim_0: THREE.Mesh;
        KIT00_FRONT_TIRE_A002_tire_0: THREE.Mesh;
        KIT00_FRONT_TIRE_A002_rim_0: THREE.Mesh;
        KIT00_FRONT_TIRE_A003_tire_0: THREE.Mesh;
        KIT00_FRONT_TIRE_A003_rim_0: THREE.Mesh;
    };
    materials: {
        misc: THREE.MeshStandardMaterial;
        color: THREE.MeshStandardMaterial;
        Material_523: THREE.MeshStandardMaterial;
        alumm: THREE.MeshStandardMaterial;
        black: THREE.MeshStandardMaterial;
        color2: THREE.MeshStandardMaterial;
        glass: THREE.MeshStandardMaterial;
        Material_293: THREE.MeshStandardMaterial;
        windows: THREE.MeshStandardMaterial;
        tire: THREE.MeshStandardMaterial;
        material: THREE.MeshStandardMaterial;
        interior: THREE.MeshStandardMaterial;
        mirror: THREE.MeshStandardMaterial;
        ["break"]: THREE.MeshStandardMaterial;
        breakglass: THREE.MeshStandardMaterial;
        headlight: THREE.MeshStandardMaterial;
        headglass: THREE.MeshStandardMaterial;
    };
    animations: GLTFAction[];
};

export function Camaro({ ...props }: JSX.IntrinsicElements["group"]) {
    const group = useRef<THREE.Group>(null);
    const { nodes, materials, animations } = useGLTF(
        "/camaro_ss/scene.gltf"
    ) as GLTFResult;
    const { actions } = useAnimations(animations, group);
    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Sketchfab_Scene">
                <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
                    <group
                        name="a2e6931bb8b243039ab757a1deaff187fbx"
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={0.01}>
                        <group name="Object_2">
                            <group name="RootNode">
                                <group
                                    name="KIT00_LEFT_HEADLIGHT_OFF_A"
                                    position={[2.15, 0.45, -0.76]}
                                    rotation={[-Math.PI / 2, 0, 0]}>
                                    <group
                                        name="Object_56"
                                        position={[-2.15, -0.76, -0.45]}>
                                        <mesh
                                            name="KIT00_LEFT_HEADLIGHT_OFF_A_misc_0"
                                            geometry={
                                                nodes
                                                    .KIT00_LEFT_HEADLIGHT_OFF_A_misc_0
                                                    .geometry
                                            }
                                            material={materials.misc}
                                        />
                                    </group>
                                </group>
                                <group
                                    name="KIT00_RIGHT_HEADLIGHT_OFF_A"
                                    position={[2.15, 0.45, 0.76]}
                                    rotation={[-Math.PI / 2, 0, 0]}>
                                    <group
                                        name="Object_83"
                                        position={[-2.15, 0.76, -0.45]}>
                                        <mesh
                                            name="KIT00_RIGHT_HEADLIGHT_OFF_A_misc_0"
                                            geometry={
                                                nodes
                                                    .KIT00_RIGHT_HEADLIGHT_OFF_A_misc_0
                                                    .geometry
                                            }
                                            material={materials.misc}
                                        />
                                    </group>
                                </group>
                                <group
                                    name="BASE_A"
                                    rotation={[-Math.PI / 2, 0, 0]}>
                                    <mesh
                                        name="BASE_A_color_0"
                                        geometry={nodes.BASE_A_color_0.geometry}
                                        material={materials.color}
                                    />
                                </group>
                                <group
                                    name="KIT00_BODY_A"
                                    rotation={[-Math.PI / 2, 0, 0]}>
                                    <mesh
                                        name="KIT00_BODY_A_Material_#523_0"
                                        geometry={
                                            nodes[
                                                "KIT00_BODY_A_Material_#523_0"
                                            ].geometry
                                        }
                                        material={materials.Material_523}
                                    />
                                    <mesh
                                        name="KIT00_BODY_A_color_0"
                                        geometry={
                                            nodes.KIT00_BODY_A_color_0.geometry
                                        }
                                        material={materials.color}
                                    />
                                    <mesh
                                        name="KIT00_BODY_A_alumm_0"
                                        geometry={
                                            nodes.KIT00_BODY_A_alumm_0.geometry
                                        }
                                        material={materials.alumm}
                                    />
                                    <mesh
                                        name="KIT00_BODY_A_black_0"
                                        geometry={
                                            nodes.KIT00_BODY_A_black_0.geometry
                                        }
                                        material={materials.black}
                                    />
                                    <mesh
                                        name="KIT00_BODY_A_misc_0"
                                        geometry={
                                            nodes.KIT00_BODY_A_misc_0.geometry
                                        }
                                        material={materials.misc}
                                    />
                                    <mesh
                                        name="KIT00_BODY_A_color2_0"
                                        geometry={
                                            nodes.KIT00_BODY_A_color2_0.geometry
                                        }
                                        material={materials.color2}
                                    />
                                </group>
                                <group
                                    name="KIT00_DOORLINE_A"
                                    rotation={[-Math.PI / 2, 0, 0]}>
                                    <mesh
                                        name="KIT00_DOORLINE_A_color2_0"
                                        geometry={
                                            nodes.KIT00_DOORLINE_A_color2_0
                                                .geometry
                                        }
                                        material={materials.color2}
                                    />
                                </group>
                                <group
                                    name="KIT00_DOOR_LEFT_A"
                                    rotation={[-Math.PI / 2, 0, 0]}>
                                    <mesh
                                        name="KIT00_DOOR_LEFT_A_color_0"
                                        geometry={
                                            nodes.KIT00_DOOR_LEFT_A_color_0
                                                .geometry
                                        }
                                        material={materials.color}
                                    />
                                    <mesh
                                        name="KIT00_DOOR_LEFT_A_alumm_0"
                                        geometry={
                                            nodes.KIT00_DOOR_LEFT_A_alumm_0
                                                .geometry
                                        }
                                        material={materials.alumm}
                                    />
                                </group>
                                <group
                                    name="KIT00_DOOR_RIGHT_A"
                                    rotation={[-Math.PI / 2, 0, 0]}>
                                    <mesh
                                        name="KIT00_DOOR_RIGHT_A_color_0"
                                        geometry={
                                            nodes.KIT00_DOOR_RIGHT_A_color_0
                                                .geometry
                                        }
                                        material={materials.color}
                                    />
                                    <mesh
                                        name="KIT00_DOOR_RIGHT_A_alumm_0"
                                        geometry={
                                            nodes.KIT00_DOOR_RIGHT_A_alumm_0
                                                .geometry
                                        }
                                        material={materials.alumm}
                                    />
                                </group>
                                <group
                                    name="KIT00_EXHAUST_A"
                                    rotation={[-Math.PI / 2, 0, 0]}>
                                    <mesh
                                        name="KIT00_EXHAUST_A_alumm_0"
                                        geometry={
                                            nodes.KIT00_EXHAUST_A_alumm_0
                                                .geometry
                                        }
                                        material={materials.alumm}
                                    />
                                </group>
                                <group
                                    name="KIT00_FRONT_BUMPER_A"
                                    rotation={[-Math.PI / 2, 0, 0]}>
                                    <mesh
                                        name="KIT00_FRONT_BUMPER_A_color_0"
                                        geometry={
                                            nodes.KIT00_FRONT_BUMPER_A_color_0
                                                .geometry
                                        }
                                        material={materials.color}
                                    />
                                    <mesh
                                        name="KIT00_FRONT_BUMPER_A_black_0"
                                        geometry={
                                            nodes.KIT00_FRONT_BUMPER_A_black_0
                                                .geometry
                                        }
                                        material={materials.black}
                                    />
                                    <mesh
                                        name="KIT00_FRONT_BUMPER_A_glass_0"
                                        geometry={
                                            nodes.KIT00_FRONT_BUMPER_A_glass_0
                                                .geometry
                                        }
                                        material={materials.glass}
                                    />
                                    <mesh
                                        name="KIT00_FRONT_BUMPER_A_alumm_0"
                                        geometry={
                                            nodes.KIT00_FRONT_BUMPER_A_alumm_0
                                                .geometry
                                        }
                                        material={materials.alumm}
                                    />
                                    <mesh
                                        name="KIT00_FRONT_BUMPER_A_Material_#293_0"
                                        geometry={
                                            nodes[
                                                "KIT00_FRONT_BUMPER_A_Material_#293_0"
                                            ].geometry
                                        }
                                        material={materials.Material_293}
                                    />
                                    <mesh
                                        name="KIT00_FRONT_BUMPER_A_misc_0"
                                        geometry={
                                            nodes.KIT00_FRONT_BUMPER_A_misc_0
                                                .geometry
                                        }
                                        material={materials.misc}
                                    />
                                </group>
                                <group
                                    name="KIT00_FRONT_BUMPER_BADGING_SET_A"
                                    rotation={[-Math.PI / 2, 0, 0]}>
                                    <mesh
                                        name="KIT00_FRONT_BUMPER_BADGING_SET_A_Material_#523_0"
                                        geometry={
                                            nodes[
                                                "KIT00_FRONT_BUMPER_BADGING_SET_A_Material_#523_0"
                                            ].geometry
                                        }
                                        material={materials.Material_523}
                                    />
                                </group>
                                <group
                                    name="KIT00_FRONT_LEFT_WINDOW_A"
                                    rotation={[-Math.PI / 2, 0, 0]}>
                                    <mesh
                                        name="KIT00_FRONT_LEFT_WINDOW_A_windows_0"
                                        geometry={
                                            nodes
                                                .KIT00_FRONT_LEFT_WINDOW_A_windows_0
                                                .geometry
                                        }
                                        material={materials.windows}
                                    />
                                </group>
                                <group
                                    name="KIT00_FRONT_RIGHT_WINDOW_A"
                                    rotation={[-Math.PI / 2, 0, 0]}>
                                    <mesh
                                        name="KIT00_FRONT_RIGHT_WINDOW_A_windows_0"
                                        geometry={
                                            nodes
                                                .KIT00_FRONT_RIGHT_WINDOW_A_windows_0
                                                .geometry
                                        }
                                        material={materials.windows}
                                    />
                                </group>
                                <group
                                    name="KIT00_FRONT_TIRE_A"
                                    position={[1.41, 0.12, 0.95]}
                                    rotation={[-Math.PI / 2, 0, 0]}>
                                    <mesh
                                        name="KIT00_FRONT_TIRE_A_tire_0"
                                        geometry={
                                            nodes.KIT00_FRONT_TIRE_A_tire_0
                                                .geometry
                                        }
                                        material={materials.tire}
                                    />
                                    <mesh
                                        name="KIT00_FRONT_TIRE_A_rim_0"
                                        geometry={
                                            nodes.KIT00_FRONT_TIRE_A_rim_0
                                                .geometry
                                        }
                                        material={materials.material}
                                    />
                                </group>
                                <group
                                    name="KIT00_FRONT_WINDOW_A"
                                    rotation={[-Math.PI / 2, 0, 0]}>
                                    <mesh
                                        name="KIT00_FRONT_WINDOW_A_windows_0"
                                        geometry={
                                            nodes.KIT00_FRONT_WINDOW_A_windows_0
                                                .geometry
                                        }
                                        material={materials.windows}
                                    />
                                </group>
                                <group
                                    name="KIT00_HOOD_A"
                                    rotation={[-Math.PI / 2, 0, 0]}>
                                    <mesh
                                        name="KIT00_HOOD_A_color_0"
                                        geometry={
                                            nodes.KIT00_HOOD_A_color_0.geometry
                                        }
                                        material={materials.color}
                                    />
                                    <mesh
                                        name="KIT00_HOOD_A_misc_0"
                                        geometry={
                                            nodes.KIT00_HOOD_A_misc_0.geometry
                                        }
                                        material={materials.misc}
                                    />
                                </group>
                                <group
                                    name="KIT00_INTERIOR_A"
                                    rotation={[-Math.PI / 2, 0, 0]}>
                                    <mesh
                                        name="KIT00_INTERIOR_A_interior_0"
                                        geometry={
                                            nodes.KIT00_INTERIOR_A_interior_0
                                                .geometry
                                        }
                                        material={materials.interior}
                                    />
                                    <mesh
                                        name="KIT00_INTERIOR_A_mirror_0"
                                        geometry={
                                            nodes.KIT00_INTERIOR_A_mirror_0
                                                .geometry
                                        }
                                        material={materials.mirror}
                                    />
                                </group>
                                <group
                                    name="KIT00_LEFT_BRAKELIGHT_A"
                                    rotation={[-Math.PI / 2, 0, 0]}>
                                    <mesh
                                        name="KIT00_LEFT_BRAKELIGHT_A_break_0"
                                        geometry={
                                            nodes
                                                .KIT00_LEFT_BRAKELIGHT_A_break_0
                                                .geometry
                                        }
                                        material={materials["break"]}
                                    />
                                </group>
                                <group
                                    name="KIT00_LEFT_BRAKELIGHT_GLASS_A"
                                    rotation={[-Math.PI / 2, 0, 0]}>
                                    <mesh
                                        name="KIT00_LEFT_BRAKELIGHT_GLASS_A_breakglass_0"
                                        geometry={
                                            nodes
                                                .KIT00_LEFT_BRAKELIGHT_GLASS_A_breakglass_0
                                                .geometry
                                        }
                                        material={materials.breakglass}
                                    />
                                </group>
                                <group
                                    name="KIT00_LEFT_HEADLIGHT_A"
                                    rotation={[-Math.PI / 2, 0, 0]}>
                                    <mesh
                                        name="KIT00_LEFT_HEADLIGHT_A_headlight_0"
                                        geometry={
                                            nodes
                                                .KIT00_LEFT_HEADLIGHT_A_headlight_0
                                                .geometry
                                        }
                                        material={materials.headlight}
                                    />
                                </group>
                                <group
                                    name="KIT00_LEFT_HEADLIGHT_GLASS_A"
                                    rotation={[-Math.PI / 2, 0, 0]}>
                                    <mesh
                                        name="KIT00_LEFT_HEADLIGHT_GLASS_A_headglass_0"
                                        geometry={
                                            nodes
                                                .KIT00_LEFT_HEADLIGHT_GLASS_A_headglass_0
                                                .geometry
                                        }
                                        material={materials.headglass}
                                    />
                                </group>
                                <group
                                    name="KIT00_LEFT_SIDE_MIRROR_A"
                                    rotation={[-Math.PI / 2, 0, 0]}>
                                    <mesh
                                        name="KIT00_LEFT_SIDE_MIRROR_A_alumm_0"
                                        geometry={
                                            nodes
                                                .KIT00_LEFT_SIDE_MIRROR_A_alumm_0
                                                .geometry
                                        }
                                        material={materials.alumm}
                                    />
                                    <mesh
                                        name="KIT00_LEFT_SIDE_MIRROR_A_mirror_0"
                                        geometry={
                                            nodes
                                                .KIT00_LEFT_SIDE_MIRROR_A_mirror_0
                                                .geometry
                                        }
                                        material={materials.mirror}
                                    />
                                </group>
                                <group
                                    name="KIT00_REAR_BUMPER_A"
                                    rotation={[-Math.PI / 2, 0, 0]}>
                                    <mesh
                                        name="KIT00_REAR_BUMPER_A_glass_0"
                                        geometry={
                                            nodes.KIT00_REAR_BUMPER_A_glass_0
                                                .geometry
                                        }
                                        material={materials.glass}
                                    />
                                    <mesh
                                        name="KIT00_REAR_BUMPER_A_color_0"
                                        geometry={
                                            nodes.KIT00_REAR_BUMPER_A_color_0
                                                .geometry
                                        }
                                        material={materials.color}
                                    />
                                    <mesh
                                        name="KIT00_REAR_BUMPER_A_misc_0"
                                        geometry={
                                            nodes.KIT00_REAR_BUMPER_A_misc_0
                                                .geometry
                                        }
                                        material={materials.misc}
                                    />
                                    <mesh
                                        name="KIT00_REAR_BUMPER_A_black_0"
                                        geometry={
                                            nodes.KIT00_REAR_BUMPER_A_black_0
                                                .geometry
                                        }
                                        material={materials.black}
                                    />
                                    <mesh
                                        name="KIT00_REAR_BUMPER_A_alumm_0"
                                        geometry={
                                            nodes.KIT00_REAR_BUMPER_A_alumm_0
                                                .geometry
                                        }
                                        material={materials.alumm}
                                    />
                                </group>
                                <group
                                    name="KIT00_REAR_BUMPER_BADGING_SET_A"
                                    rotation={[-Math.PI / 2, 0, 0]}>
                                    <mesh
                                        name="KIT00_REAR_BUMPER_BADGING_SET_A_Material_#523_0"
                                        geometry={
                                            nodes[
                                                "KIT00_REAR_BUMPER_BADGING_SET_A_Material_#523_0"
                                            ].geometry
                                        }
                                        material={materials.Material_523}
                                    />
                                    <mesh
                                        name="KIT00_REAR_BUMPER_BADGING_SET_A_alumm_0"
                                        geometry={
                                            nodes
                                                .KIT00_REAR_BUMPER_BADGING_SET_A_alumm_0
                                                .geometry
                                        }
                                        material={materials.alumm}
                                    />
                                    <mesh
                                        name="KIT00_REAR_BUMPER_BADGING_SET_A_misc_0"
                                        geometry={
                                            nodes
                                                .KIT00_REAR_BUMPER_BADGING_SET_A_misc_0
                                                .geometry
                                        }
                                        material={materials.misc}
                                    />
                                    <mesh
                                        name="KIT00_REAR_BUMPER_BADGING_SET_A_black_0"
                                        geometry={
                                            nodes
                                                .KIT00_REAR_BUMPER_BADGING_SET_A_black_0
                                                .geometry
                                        }
                                        material={materials.black}
                                    />
                                </group>
                                <group
                                    name="KIT00_REAR_WINDOW_A"
                                    rotation={[-Math.PI / 2, 0, 0]}>
                                    <mesh
                                        name="KIT00_REAR_WINDOW_A_windows_0"
                                        geometry={
                                            nodes.KIT00_REAR_WINDOW_A_windows_0
                                                .geometry
                                        }
                                        material={materials.windows}
                                    />
                                </group>
                                <group
                                    name="KIT00_RIGHT_BRAKELIGHT_A"
                                    rotation={[-Math.PI / 2, 0, 0]}>
                                    <mesh
                                        name="KIT00_RIGHT_BRAKELIGHT_A_break_0"
                                        geometry={
                                            nodes
                                                .KIT00_RIGHT_BRAKELIGHT_A_break_0
                                                .geometry
                                        }
                                        material={materials["break"]}
                                    />
                                </group>
                                <group
                                    name="KIT00_RIGHT_BRAKELIGHT_GLASS_A"
                                    rotation={[-Math.PI / 2, 0, 0]}>
                                    <mesh
                                        name="KIT00_RIGHT_BRAKELIGHT_GLASS_A_breakglass_0"
                                        geometry={
                                            nodes
                                                .KIT00_RIGHT_BRAKELIGHT_GLASS_A_breakglass_0
                                                .geometry
                                        }
                                        material={materials.breakglass}
                                    />
                                </group>
                                <group
                                    name="KIT00_RIGHT_HEADLIGHT_A"
                                    rotation={[-Math.PI / 2, 0, 0]}>
                                    <mesh
                                        name="KIT00_RIGHT_HEADLIGHT_A_headlight_0"
                                        geometry={
                                            nodes
                                                .KIT00_RIGHT_HEADLIGHT_A_headlight_0
                                                .geometry
                                        }
                                        material={materials.headlight}
                                    />
                                </group>
                                <group
                                    name="KIT00_RIGHT_HEADLIGHT_GLASS_A"
                                    rotation={[-Math.PI / 2, 0, 0]}>
                                    <mesh
                                        name="KIT00_RIGHT_HEADLIGHT_GLASS_A_headglass_0"
                                        geometry={
                                            nodes
                                                .KIT00_RIGHT_HEADLIGHT_GLASS_A_headglass_0
                                                .geometry
                                        }
                                        material={materials.headglass}
                                    />
                                </group>
                                <group
                                    name="KIT00_RIGHT_SIDE_MIRROR_A"
                                    rotation={[-Math.PI / 2, 0, 0]}>
                                    <mesh
                                        name="KIT00_RIGHT_SIDE_MIRROR_A_alumm_0"
                                        geometry={
                                            nodes
                                                .KIT00_RIGHT_SIDE_MIRROR_A_alumm_0
                                                .geometry
                                        }
                                        material={materials.alumm}
                                    />
                                    <mesh
                                        name="KIT00_RIGHT_SIDE_MIRROR_A_mirror_0"
                                        geometry={
                                            nodes
                                                .KIT00_RIGHT_SIDE_MIRROR_A_mirror_0
                                                .geometry
                                        }
                                        material={materials.mirror}
                                    />
                                </group>
                                <group
                                    name="KIT00_ROOF_A"
                                    rotation={[-Math.PI / 2, 0, 0]}>
                                    <mesh
                                        name="KIT00_ROOF_A_color_0"
                                        geometry={
                                            nodes.KIT00_ROOF_A_color_0.geometry
                                        }
                                        material={materials.color}
                                    />
                                    <mesh
                                        name="KIT00_ROOF_A_alumm_0"
                                        geometry={
                                            nodes.KIT00_ROOF_A_alumm_0.geometry
                                        }
                                        material={materials.alumm}
                                    />
                                </group>
                                <group
                                    name="KIT00_SKIRT_A"
                                    rotation={[-Math.PI / 2, 0, 0]}>
                                    <mesh
                                        name="KIT00_SKIRT_A_Material_#523_0"
                                        geometry={
                                            nodes[
                                                "KIT00_SKIRT_A_Material_#523_0"
                                            ].geometry
                                        }
                                        material={materials.Material_523}
                                    />
                                    <mesh
                                        name="KIT00_SKIRT_A_color2_0"
                                        geometry={
                                            nodes.KIT00_SKIRT_A_color2_0
                                                .geometry
                                        }
                                        material={materials.color2}
                                    />
                                    <mesh
                                        name="KIT00_SKIRT_A_black_0"
                                        geometry={
                                            nodes.KIT00_SKIRT_A_black_0.geometry
                                        }
                                        material={materials.black}
                                    />
                                    <mesh
                                        name="KIT00_SKIRT_A_color_0"
                                        geometry={
                                            nodes.KIT00_SKIRT_A_color_0.geometry
                                        }
                                        material={materials.color}
                                    />
                                    <mesh
                                        name="KIT00_SKIRT_A_alumm_0"
                                        geometry={
                                            nodes.KIT00_SKIRT_A_alumm_0.geometry
                                        }
                                        material={materials.alumm}
                                    />
                                </group>
                                <group
                                    name="KIT00_SPOILER_A"
                                    rotation={[-Math.PI / 2, 0, 0]}>
                                    <mesh
                                        name="KIT00_SPOILER_A_color_0"
                                        geometry={
                                            nodes.KIT00_SPOILER_A_color_0
                                                .geometry
                                        }
                                        material={materials.color}
                                    />
                                </group>
                                <group
                                    name="KIT00_FRONT_TIRE_A001"
                                    position={[-1.34, 0.12, 0.95]}
                                    rotation={[-Math.PI / 2, 0, 0]}>
                                    <mesh
                                        name="KIT00_FRONT_TIRE_A001_tire_0"
                                        geometry={
                                            nodes.KIT00_FRONT_TIRE_A001_tire_0
                                                .geometry
                                        }
                                        material={materials.tire}
                                    />
                                    <mesh
                                        name="KIT00_FRONT_TIRE_A001_rim_0"
                                        geometry={
                                            nodes.KIT00_FRONT_TIRE_A001_rim_0
                                                .geometry
                                        }
                                        material={materials.material}
                                    />
                                </group>
                                <group
                                    name="KIT00_FRONT_TIRE_A002"
                                    position={[-1.34, 0.12, -0.95]}
                                    rotation={[-Math.PI / 2, 0, -Math.PI]}>
                                    <mesh
                                        name="KIT00_FRONT_TIRE_A002_tire_0"
                                        geometry={
                                            nodes.KIT00_FRONT_TIRE_A002_tire_0
                                                .geometry
                                        }
                                        material={materials.tire}
                                    />
                                    <mesh
                                        name="KIT00_FRONT_TIRE_A002_rim_0"
                                        geometry={
                                            nodes.KIT00_FRONT_TIRE_A002_rim_0
                                                .geometry
                                        }
                                        material={materials.material}
                                    />
                                </group>
                                <group
                                    name="KIT00_FRONT_TIRE_A003"
                                    position={[1.41, 0.12, -0.95]}
                                    rotation={[-Math.PI / 2, 0, -Math.PI]}>
                                    <mesh
                                        name="KIT00_FRONT_TIRE_A003_tire_0"
                                        geometry={
                                            nodes.KIT00_FRONT_TIRE_A003_tire_0
                                                .geometry
                                        }
                                        material={materials.tire}
                                    />
                                    <mesh
                                        name="KIT00_FRONT_TIRE_A003_rim_0"
                                        geometry={
                                            nodes.KIT00_FRONT_TIRE_A003_rim_0
                                                .geometry
                                        }
                                        material={materials.material}
                                    />
                                </group>
                            </group>
                        </group>
                    </group>
                </group>
            </group>
        </group>
    );
}

useGLTF.preload("/camaro_ss/scene.gltf");
