/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: JandroS (https://sketchfab.com/JandroS)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/parzivals-delorean-dmc-12-6bcaee578c8e4dbbbaf5fdb746e5ff8c
title: Parzival's DeLorean DMC-12
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
    nodes: {
        Back_Body_Material_0: THREE.Mesh;
        Mid_Lower_Part_Material006_0: THREE.Mesh;
        Back_Glass_frame_Material_0: THREE.Mesh;
        BackLights_and_Plate_Material001_0: THREE.Mesh;
        BackLights_and_Plate_Material007_0: THREE.Mesh;
        BackLights_and_Plate_Material013_0: THREE.Mesh;
        BackLights_and_Plate_Material012_0: THREE.Mesh;
        BackLights_and_Plate_Material011_0: THREE.Mesh;
        Body_Front_Material_0: THREE.Mesh;
        Lower_Front_Body_Material006_0: THREE.Mesh;
        AntiWheelLight_Front_Material006_0: THREE.Mesh;
        AntiWheelLight_Back_Material006_0: THREE.Mesh;
        Doors_Material_0: THREE.Mesh;
        Front_Grille_Material002_0: THREE.Mesh;
        Front_Lights_Material_0: THREE.Mesh;
        Grill_Material001_0: THREE.Mesh;
        DMCLogo_Material005_0: THREE.Mesh;
        Top_T_Material_0: THREE.Mesh;
        Trunk_Material002_0: THREE.Mesh;
        Lower_trunk_Material006_0: THREE.Mesh;
        Tubos_de_escape_Material003_0: THREE.Mesh;
        Retrovisores_Material001_0: THREE.Mesh;
        Retrovisores_Material004_0: THREE.Mesh;
        LightGlass_Glass_0: THREE.Mesh;
        Back_Body002_Material006_0: THREE.Mesh;
        BackLights_and_Plate001_Material019_0: THREE.Mesh;
        Front_Wheel_Llanta_Material009_0: THREE.Mesh;
        Back_Wheel_Llanta_Material009_0: THREE.Mesh;
        Tire_Front_Material010_0: THREE.Mesh;
        Tire_Back_Material010_0: THREE.Mesh;
        WheelPlate_Material006_0: THREE.Mesh;
        WheelPlate_Back_Material006_0: THREE.Mesh;
        Front_Glass_Glass_0: THREE.Mesh;
        Door_Glass_Material003_0: THREE.Mesh;
        Door_Glass_Glass_0: THREE.Mesh;
        RightLight1_Light1_0: THREE.Mesh;
        RightLight2_Light1_0: THREE.Mesh;
        LeftLight1_Light1_0: THREE.Mesh;
        LeftLight2_Light1_0: THREE.Mesh;
        OrangeLights_Material015_0: THREE.Mesh;
        Cube_Material001_0: THREE.Mesh;
        Cube_Material_0: THREE.Mesh;
        Cube_Material016_0: THREE.Mesh;
        Cube_Material006_0: THREE.Mesh;
        Cube_Material014_0: THREE.Mesh;
        Cube_Material017_0: THREE.Mesh;
        Cube_Material018_0: THREE.Mesh;
        Cube_Material010_0: THREE.Mesh;
        Cube_Material022_0: THREE.Mesh;
        Cube_Material023_0: THREE.Mesh;
        Cube_Material024_0: THREE.Mesh;
        Cube_Material025_0: THREE.Mesh;
        Cube_Material026_0: THREE.Mesh;
    };
    materials: {
        Material: THREE.MeshStandardMaterial;
        ["Material.006"]: THREE.MeshStandardMaterial;
        ["Material.001"]: THREE.MeshStandardMaterial;
        ["Material.007"]: THREE.MeshStandardMaterial;
        ["Material.013"]: THREE.MeshStandardMaterial;
        ["Material.012"]: THREE.MeshStandardMaterial;
        ["Material.011"]: THREE.MeshStandardMaterial;
        ["Material.002"]: THREE.MeshStandardMaterial;
        ["Material.005"]: THREE.MeshStandardMaterial;
        ["Material.003"]: THREE.MeshStandardMaterial;
        ["Material.004"]: THREE.MeshPhysicalMaterial;
        Glass: THREE.MeshStandardMaterial;
        ["Material.019"]: THREE.MeshStandardMaterial;
        ["Material.009"]: THREE.MeshStandardMaterial;
        ["Material.010"]: THREE.MeshStandardMaterial;
        Light1: THREE.MeshStandardMaterial;
        ["Material.015"]: THREE.MeshStandardMaterial;
        ["Material.016"]: THREE.MeshStandardMaterial;
        ["Material.014"]: THREE.MeshStandardMaterial;
        ["Material.017"]: THREE.MeshStandardMaterial;
        ["Material.018"]: THREE.MeshStandardMaterial;
        ["Material.022"]: THREE.MeshStandardMaterial;
        ["Material.023"]: THREE.MeshStandardMaterial;
        ["Material.024"]: THREE.MeshStandardMaterial;
        ["Material.025"]: THREE.MeshStandardMaterial;
        ["Material.026"]: THREE.MeshStandardMaterial;
    };
};

export function Delorean({ ...props }: JSX.IntrinsicElements["group"]) {
    const group = useRef<THREE.Group>(null);
    const { nodes, materials } = useGLTF(
        "/parzivals_delorean_dmc-12/scene.gltf"
    ) as GLTFResult;
    return (
        <group ref={group} {...props} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
                <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
                    <group
                        position={[0, 3.24, 0]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}>
                        <mesh
                            geometry={nodes.Back_Body_Material_0.geometry}
                            material={materials.Material}
                        />
                    </group>
                    <group
                        position={[0, 4.35, 0]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}>
                        <mesh
                            geometry={
                                nodes.Mid_Lower_Part_Material006_0.geometry
                            }
                            material={materials["Material.006"]}
                        />
                    </group>
                    <group
                        position={[0, 3.77, 0]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[100.54, 100, 100]}>
                        <mesh
                            geometry={
                                nodes.Back_Glass_frame_Material_0.geometry
                            }
                            material={materials.Material}
                        />
                    </group>
                    <group
                        position={[0, 3.24, 9.18]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}>
                        <mesh
                            geometry={
                                nodes.BackLights_and_Plate_Material001_0
                                    .geometry
                            }
                            material={materials["Material.001"]}
                        />
                        <mesh
                            geometry={
                                nodes.BackLights_and_Plate_Material007_0
                                    .geometry
                            }
                            material={materials["Material.007"]}
                        />
                        <mesh
                            geometry={
                                nodes.BackLights_and_Plate_Material013_0
                                    .geometry
                            }
                            material={materials["Material.013"]}
                        />
                        <mesh
                            geometry={
                                nodes.BackLights_and_Plate_Material012_0
                                    .geometry
                            }
                            material={materials["Material.012"]}
                        />
                        <mesh
                            geometry={
                                nodes.BackLights_and_Plate_Material011_0
                                    .geometry
                            }
                            material={materials["Material.011"]}
                        />
                    </group>
                    <group
                        position={[0, 3.24, 0]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}>
                        <mesh
                            geometry={nodes.Body_Front_Material_0.geometry}
                            material={materials.Material}
                        />
                    </group>
                    <group
                        position={[0, 3.24, 0]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}>
                        <mesh
                            geometry={
                                nodes.Lower_Front_Body_Material006_0.geometry
                            }
                            material={materials["Material.006"]}
                        />
                    </group>
                    <group
                        position={[0, 4.77, 0]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}>
                        <mesh
                            geometry={
                                nodes.AntiWheelLight_Front_Material006_0
                                    .geometry
                            }
                            material={materials["Material.006"]}
                        />
                    </group>
                    <group
                        position={[0, 89.86, -18.58]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}>
                        <mesh
                            geometry={
                                nodes.AntiWheelLight_Back_Material006_0.geometry
                            }
                            material={materials["Material.006"]}
                        />
                    </group>
                    <group
                        position={[0, 3.24, 0]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}>
                        <mesh
                            geometry={nodes.Doors_Material_0.geometry}
                            material={materials.Material}
                        />
                    </group>
                    <group
                        position={[0, 3.24, 0.73]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}>
                        <mesh
                            geometry={nodes.Front_Grille_Material002_0.geometry}
                            material={materials["Material.002"]}
                        />
                    </group>
                    <group
                        position={[0, 3.24, 0.73]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}>
                        <mesh
                            geometry={nodes.Front_Lights_Material_0.geometry}
                            material={materials.Material}
                        />
                    </group>
                    <group
                        position={[0, 89.86, -18.58]}
                        rotation={[-1.79, 0, 0]}
                        scale={100}>
                        <mesh
                            geometry={nodes.Grill_Material001_0.geometry}
                            material={materials["Material.001"]}
                        />
                    </group>
                    <group
                        position={[0, 83.69, -15.99]}
                        rotation={[-0.4, 0, 0]}
                        scale={[7.04, 1.65, 7.04]}>
                        <mesh
                            geometry={nodes.DMCLogo_Material005_0.geometry}
                            material={materials["Material.005"]}
                        />
                    </group>
                    <group
                        position={[0, 3.24, 0]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}>
                        <mesh
                            geometry={nodes.Top_T_Material_0.geometry}
                            material={materials.Material}
                        />
                    </group>
                    <group
                        position={[0, 3.24, 0]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}>
                        <mesh
                            geometry={nodes.Trunk_Material002_0.geometry}
                            material={materials["Material.002"]}
                        />
                    </group>
                    <group
                        position={[0, 4.03, 0]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}>
                        <mesh
                            geometry={nodes.Lower_trunk_Material006_0.geometry}
                            material={materials["Material.006"]}
                        />
                    </group>
                    <group
                        position={[0, 4.03, 0]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}>
                        <mesh
                            geometry={
                                nodes.Tubos_de_escape_Material003_0.geometry
                            }
                            material={materials["Material.003"]}
                        />
                    </group>
                    <group
                        position={[0, 3.24, 0]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}>
                        <mesh
                            geometry={nodes.Retrovisores_Material001_0.geometry}
                            material={materials["Material.001"]}
                        />
                        <mesh
                            geometry={nodes.Retrovisores_Material004_0.geometry}
                            material={materials["Material.004"]}
                        />
                    </group>
                    <group position={[0, 3.24, 0]} scale={100}>
                        <mesh
                            geometry={nodes.LightGlass_Glass_0.geometry}
                            material={materials.Glass}
                        />
                    </group>
                    <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                        <mesh
                            geometry={nodes.Back_Body002_Material006_0.geometry}
                            material={materials["Material.006"]}
                        />
                    </group>
                    <group
                        position={[0, 3.24, 9.18]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}>
                        <mesh
                            geometry={
                                nodes.BackLights_and_Plate001_Material019_0
                                    .geometry
                            }
                            material={materials["Material.019"]}
                        />
                    </group>
                    <group
                        position={[0, 3.24, 0]}
                        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                        scale={[52.55, 49.97, 99.95]}>
                        <mesh
                            geometry={
                                nodes.Front_Wheel_Llanta_Material009_0.geometry
                            }
                            material={materials["Material.009"]}
                        />
                    </group>
                    <group
                        position={[0, 3.24, 0]}
                        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                        scale={[52.55, 49.97, 99.95]}>
                        <mesh
                            geometry={
                                nodes.Back_Wheel_Llanta_Material009_0.geometry
                            }
                            material={materials["Material.009"]}
                        />
                    </group>
                    <group
                        position={[0, 3.24, 0]}
                        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                        scale={100}>
                        <mesh
                            geometry={nodes.Tire_Front_Material010_0.geometry}
                            material={materials["Material.010"]}
                        />
                    </group>
                    <group
                        position={[0, 3.24, 0]}
                        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                        scale={100}>
                        <mesh
                            geometry={nodes.Tire_Back_Material010_0.geometry}
                            material={materials["Material.010"]}
                        />
                    </group>
                    <group
                        position={[0, 3.24, 0]}
                        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                        scale={100.9}>
                        <mesh
                            geometry={nodes.WheelPlate_Material006_0.geometry}
                            material={materials["Material.006"]}
                        />
                    </group>
                    <group
                        position={[0, 3.24, 0]}
                        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                        scale={100.9}>
                        <mesh
                            geometry={
                                nodes.WheelPlate_Back_Material006_0.geometry
                            }
                            material={materials["Material.006"]}
                        />
                    </group>
                    <group
                        position={[0, -2.4, -3.08]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}>
                        <mesh
                            geometry={nodes.Front_Glass_Glass_0.geometry}
                            material={materials.Glass}
                        />
                    </group>
                    <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                        <mesh
                            geometry={nodes.Door_Glass_Material003_0.geometry}
                            material={materials["Material.003"]}
                        />
                        <mesh
                            geometry={nodes.Door_Glass_Glass_0.geometry}
                            material={materials.Glass}
                        />
                    </group>
                    <group position={[60.43, 82.13, -34.36]} scale={27.66}>
                        <mesh
                            geometry={nodes.RightLight1_Light1_0.geometry}
                            material={materials.Light1}
                        />
                    </group>
                    <group position={[85.58, 82.13, -34.36]} scale={27.66}>
                        <mesh
                            geometry={nodes.RightLight2_Light1_0.geometry}
                            material={materials.Light1}
                        />
                    </group>
                    <group position={[-94.83, 82.13, -34.36]} scale={27.66}>
                        <mesh
                            geometry={nodes.LeftLight1_Light1_0.geometry}
                            material={materials.Light1}
                        />
                    </group>
                    <group position={[-69.68, 82.13, -34.36]} scale={27.66}>
                        <mesh
                            geometry={nodes.LeftLight2_Light1_0.geometry}
                            material={materials.Light1}
                        />
                    </group>
                    <group rotation={[0.73, 0, 0]} scale={27.66}>
                        <mesh
                            geometry={nodes.OrangeLights_Material015_0.geometry}
                            material={materials["Material.015"]}
                        />
                    </group>
                    <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                        <mesh
                            geometry={nodes.Cube_Material001_0.geometry}
                            material={materials["Material.001"]}
                        />
                        <mesh
                            geometry={nodes.Cube_Material_0.geometry}
                            material={materials.Material}
                        />
                        <mesh
                            geometry={nodes.Cube_Material016_0.geometry}
                            material={materials["Material.016"]}
                        />
                        <mesh
                            geometry={nodes.Cube_Material006_0.geometry}
                            material={materials["Material.006"]}
                        />
                        <mesh
                            geometry={nodes.Cube_Material014_0.geometry}
                            material={materials["Material.014"]}
                        />
                        <mesh
                            geometry={nodes.Cube_Material017_0.geometry}
                            material={materials["Material.017"]}
                        />
                        <mesh
                            geometry={nodes.Cube_Material018_0.geometry}
                            material={materials["Material.018"]}
                        />
                        <mesh
                            geometry={nodes.Cube_Material010_0.geometry}
                            material={materials["Material.010"]}
                        />
                        <mesh
                            geometry={nodes.Cube_Material022_0.geometry}
                            material={materials["Material.022"]}
                        />
                        <mesh
                            geometry={nodes.Cube_Material023_0.geometry}
                            material={materials["Material.023"]}
                        />
                        <mesh
                            geometry={nodes.Cube_Material024_0.geometry}
                            material={materials["Material.024"]}
                        />
                        <mesh
                            geometry={nodes.Cube_Material025_0.geometry}
                            material={materials["Material.025"]}
                        />
                        <mesh
                            geometry={nodes.Cube_Material026_0.geometry}
                            material={materials["Material.026"]}
                        />
                    </group>
                </group>
            </group>
        </group>
    );
}

useGLTF.preload("/parzivals_delorean_dmc-12/scene.gltf");
