/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Lucas Soler (https://sketchfab.com/lucassoler)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/fiat-850-spider-8ea03b3cbb9f439ea82a68ddbeb5f6ae
title: Fiat 850 Spider
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
    nodes: {
        Object_4: THREE.Mesh;
        Object_6: THREE.Mesh;
        Object_7: THREE.Mesh;
        Object_9: THREE.Mesh;
        Object_11: THREE.Mesh;
        Object_13: THREE.Mesh;
        Object_15: THREE.Mesh;
        Object_17: THREE.Mesh;
        Object_19: THREE.Mesh;
        Object_21: THREE.Mesh;
        Object_23: THREE.Mesh;
        Object_25: THREE.Mesh;
        Object_27: THREE.Mesh;
        Object_28: THREE.Mesh;
        Object_30: THREE.Mesh;
        Object_32: THREE.Mesh;
        Object_34: THREE.Mesh;
        Object_36: THREE.Mesh;
        Object_38: THREE.Mesh;
        Object_40: THREE.Mesh;
        Object_42: THREE.Mesh;
        Object_43: THREE.Mesh;
        Object_45: THREE.Mesh;
        Object_46: THREE.Mesh;
        Object_48: THREE.Mesh;
        Object_50: THREE.Mesh;
        Object_52: THREE.Mesh;
        Object_54: THREE.Mesh;
        Object_55: THREE.Mesh;
        Object_57: THREE.Mesh;
        Object_59: THREE.Mesh;
        Object_61: THREE.Mesh;
        Object_62: THREE.Mesh;
        Object_64: THREE.Mesh;
        Object_66: THREE.Mesh;
        Object_67: THREE.Mesh;
        Object_69: THREE.Mesh;
        Object_71: THREE.Mesh;
        Object_73: THREE.Mesh;
        Object_75: THREE.Mesh;
        Object_77: THREE.Mesh;
        Object_79: THREE.Mesh;
        Object_81: THREE.Mesh;
        Object_83: THREE.Mesh;
        Object_85: THREE.Mesh;
        Object_87: THREE.Mesh;
        Object_89: THREE.Mesh;
        Object_91: THREE.Mesh;
        Object_93: THREE.Mesh;
        Object_95: THREE.Mesh;
        Object_97: THREE.Mesh;
        Object_99: THREE.Mesh;
        Object_101: THREE.Mesh;
        Object_103: THREE.Mesh;
        Object_105: THREE.Mesh;
        Object_107: THREE.Mesh;
        Object_109: THREE.Mesh;
        Object_111: THREE.Mesh;
        Object_113: THREE.Mesh;
        Object_115: THREE.Mesh;
        Object_117: THREE.Mesh;
        Object_118: THREE.Mesh;
        Object_120: THREE.Mesh;
        Object_121: THREE.Mesh;
        Object_123: THREE.Mesh;
        Object_124: THREE.Mesh;
        Object_126: THREE.Mesh;
        Object_127: THREE.Mesh;
        Object_129: THREE.Mesh;
        Object_130: THREE.Mesh;
        Object_132: THREE.Mesh;
        Object_134: THREE.Mesh;
        Object_136: THREE.Mesh;
        Object_138: THREE.Mesh;
        Object_140: THREE.Mesh;
        Object_141: THREE.Mesh;
        Object_142: THREE.Mesh;
        Object_144: THREE.Mesh;
        Object_146: THREE.Mesh;
        Object_148: THREE.Mesh;
        Object_149: THREE.Mesh;
        Object_151: THREE.Mesh;
        Object_152: THREE.Mesh;
        Object_154: THREE.Mesh;
        Object_155: THREE.Mesh;
        Object_157: THREE.Mesh;
        Object_158: THREE.Mesh;
        Object_160: THREE.Mesh;
        Object_161: THREE.Mesh;
        Object_163: THREE.Mesh;
        Object_164: THREE.Mesh;
        Object_166: THREE.Mesh;
        Object_168: THREE.Mesh;
        Object_170: THREE.Mesh;
        Object_175: THREE.Mesh;
        Object_176: THREE.Mesh;
        Object_172: THREE.Mesh;
        Object_173: THREE.Mesh;
        Object_178: THREE.Mesh;
        Object_180: THREE.Mesh;
        Object_182: THREE.Mesh;
        Object_184: THREE.Mesh;
        Object_186: THREE.Mesh;
        Object_188: THREE.Mesh;
        Object_190: THREE.Mesh;
        Object_191: THREE.Mesh;
        Object_193: THREE.Mesh;
        Object_195: THREE.Mesh;
        Object_197: THREE.Mesh;
        Object_199: THREE.Mesh;
        Object_201: THREE.Mesh;
        Object_203: THREE.Mesh;
        Object_205: THREE.Mesh;
        Object_206: THREE.Mesh;
        Object_208: THREE.Mesh;
        Object_209: THREE.Mesh;
        Object_211: THREE.Mesh;
        Object_212: THREE.Mesh;
        Object_214: THREE.Mesh;
        Object_215: THREE.Mesh;
        Object_217: THREE.Mesh;
        Object_219: THREE.Mesh;
        Object_223: THREE.Mesh;
        Object_225: THREE.Mesh;
        Object_227: THREE.Mesh;
        Object_221: THREE.Mesh;
        Object_229: THREE.Mesh;
        Object_230: THREE.Mesh;
        Object_232: THREE.Mesh;
        Object_237: THREE.Mesh;
        Object_238: THREE.Mesh;
        Object_239: THREE.Mesh;
        Object_241: THREE.Mesh;
        Object_234: THREE.Mesh;
        Object_235: THREE.Mesh;
        Object_243: THREE.Mesh;
        Object_244: THREE.Mesh;
        Object_246: THREE.Mesh;
        Object_248: THREE.Mesh;
        Object_249: THREE.Mesh;
        Object_251: THREE.Mesh;
        Object_253: THREE.Mesh;
    };
    materials: {
        Chrome: THREE.MeshStandardMaterial;
        Rubber: THREE.MeshStandardMaterial;
        ["Cristal.001"]: THREE.MeshPhysicalMaterial;
        Cristal: THREE.MeshPhysicalMaterial;
        paint: THREE.MeshPhysicalMaterial;
        ["Chrome.003"]: THREE.MeshStandardMaterial;
        ["Material.001"]: THREE.MeshPhysicalMaterial;
        ["Material.003"]: THREE.MeshStandardMaterial;
        ["Material.002"]: THREE.MeshStandardMaterial;
        ["Chrome.002"]: THREE.MeshStandardMaterial;
        metal: THREE.MeshStandardMaterial;
        ["Material.004"]: THREE.MeshStandardMaterial;
        ["Material.010"]: THREE.MeshStandardMaterial;
        ["Material.011"]: THREE.MeshStandardMaterial;
        lightbulb: THREE.MeshStandardMaterial;
        Exhaust: THREE.MeshStandardMaterial;
        ["Rubber.003"]: THREE.MeshStandardMaterial;
        Wood: THREE.MeshStandardMaterial;
        ["matte-black"]: THREE.MeshStandardMaterial;
        Cluster: THREE.MeshStandardMaterial;
        ["Cristal.002"]: THREE.MeshPhysicalMaterial;
        ["Material.008"]: THREE.MeshStandardMaterial;
        ["metal.001"]: THREE.MeshStandardMaterial;
        ["Rubber.001"]: THREE.MeshStandardMaterial;
        ["Material.007"]: THREE.MeshStandardMaterial;
        ["Rubber.002"]: THREE.MeshStandardMaterial;
        material_0: THREE.MeshStandardMaterial;
        Seats: THREE.MeshStandardMaterial;
        tire_side: THREE.MeshStandardMaterial;
        tire_tread: THREE.MeshStandardMaterial;
        ["metal.002"]: THREE.MeshStandardMaterial;
    };
};

export function Fiat({ ...props }: JSX.IntrinsicElements["group"]) {
    const group = useRef<THREE.Group>(null);
    const { nodes, materials } = useGLTF(
        "/fiat_850_spider/scene.gltf"
    ) as GLTFResult;
    return (
        <group ref={group} {...props} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
                <group rotation={[Math.PI / 2, 0, 0]}>
                    <group position={[0, -1.61, -100.17]}>
                        <mesh
                            geometry={nodes.Object_4.geometry}
                            material={materials.Chrome}
                        />
                    </group>
                    <group
                        position={[0, -17.52, 177.45]}
                        rotation={[-Math.PI, 0, -Math.PI]}>
                        <mesh
                            geometry={nodes.Object_6.geometry}
                            material={materials.Rubber}
                        />
                        <mesh
                            geometry={nodes.Object_7.geometry}
                            material={materials.Chrome}
                        />
                    </group>
                    <group position={[0, -1.61, -100.17]}>
                        <mesh
                            geometry={nodes.Object_9.geometry}
                            material={materials.Rubber}
                        />
                    </group>
                    <group position={[0, -1.61, -100.17]}>
                        <mesh
                            geometry={nodes.Object_11.geometry}
                            material={materials["Cristal.001"]}
                        />
                    </group>
                    <group position={[0, -1.61, -100.17]}>
                        <mesh
                            geometry={nodes.Object_13.geometry}
                            material={materials.Cristal}
                        />
                    </group>
                    <group position={[0, -1.61, -100.17]}>
                        <mesh
                            geometry={nodes.Object_15.geometry}
                            material={materials.Chrome}
                        />
                    </group>
                    <group position={[0, -1.61, -100.17]}>
                        <mesh
                            geometry={nodes.Object_17.geometry}
                            material={materials.paint}
                        />
                    </group>
                    <group position={[0, -1.61, -100.17]}>
                        <mesh
                            geometry={nodes.Object_19.geometry}
                            material={materials.paint}
                        />
                    </group>
                    <group position={[0, -1.61, -100.17]}>
                        <mesh
                            geometry={nodes.Object_21.geometry}
                            material={materials.paint}
                        />
                    </group>
                    <group position={[0, -1.61, -100.17]}>
                        <mesh
                            geometry={nodes.Object_23.geometry}
                            material={materials.paint}
                        />
                    </group>
                    <group position={[0, -1.61, -100.17]}>
                        <mesh
                            geometry={nodes.Object_25.geometry}
                            material={materials["Chrome.003"]}
                        />
                    </group>
                    <group position={[0, -1.61, -100.17]}>
                        <mesh
                            geometry={nodes.Object_27.geometry}
                            material={materials["Material.001"]}
                        />
                        <mesh
                            geometry={nodes.Object_28.geometry}
                            material={materials["Material.003"]}
                        />
                    </group>
                    <group position={[-46.92, -0.49, 177.15]}>
                        <mesh
                            geometry={nodes.Object_30.geometry}
                            material={materials["Material.002"]}
                        />
                    </group>
                    <group
                        position={[-46.23, 1.02, 176.48]}
                        rotation={[-1.65, 0.09, 0.1]}
                        scale={0.01}>
                        <mesh
                            geometry={nodes.Object_32.geometry}
                            material={materials["Chrome.002"]}
                        />
                    </group>
                    <group
                        position={[-57.92, -0.85, 178.34]}
                        rotation={[0.04, -0.1, 0]}>
                        <mesh
                            geometry={nodes.Object_34.geometry}
                            material={materials.metal}
                        />
                    </group>
                    <group position={[-36.88, -0.5, 179.85]}>
                        <mesh
                            geometry={nodes.Object_36.geometry}
                            material={materials["Material.004"]}
                        />
                    </group>
                    <group position={[-34.11, 20.94, 110.96]}>
                        <mesh
                            geometry={nodes.Object_38.geometry}
                            material={materials.Rubber}
                        />
                    </group>
                    <group position={[-34.11, 20.94, 110.96]}>
                        <mesh
                            geometry={nodes.Object_40.geometry}
                            material={materials.Chrome}
                        />
                    </group>
                    <group
                        position={[-34.27, 22.24, 81.9]}
                        rotation={[0.01, 0, 0.06]}>
                        <mesh
                            geometry={nodes.Object_42.geometry}
                            material={materials.Chrome}
                        />
                        <mesh
                            geometry={nodes.Object_43.geometry}
                            material={materials.Rubber}
                        />
                    </group>
                    <group position={[0, 23.06, 82.35]} rotation={[0.02, 0, 0]}>
                        <mesh
                            geometry={nodes.Object_45.geometry}
                            material={materials.Chrome}
                        />
                        <mesh
                            geometry={nodes.Object_46.geometry}
                            material={materials.Rubber}
                        />
                    </group>
                    <group position={[0, -1.61, -100.17]}>
                        <mesh
                            geometry={nodes.Object_48.geometry}
                            material={materials.Chrome}
                        />
                    </group>
                    <group position={[0, -1.61, -99.35]}>
                        <mesh
                            geometry={nodes.Object_50.geometry}
                            material={materials.Chrome}
                        />
                    </group>
                    <group position={[-61.81, 19.17, 53.76]}>
                        <mesh
                            geometry={nodes.Object_52.geometry}
                            material={materials.Chrome}
                        />
                    </group>
                    <group position={[0, -1.61, -100.17]}>
                        <mesh
                            geometry={nodes.Object_54.geometry}
                            material={materials.Chrome}
                        />
                        <mesh
                            geometry={nodes.Object_55.geometry}
                            material={materials.Rubber}
                        />
                    </group>
                    <group position={[0, -1.61, -100.17]}>
                        <mesh
                            geometry={nodes.Object_57.geometry}
                            material={materials.Rubber}
                        />
                    </group>
                    <group
                        position={[-63.93, 18.96, -20.11]}
                        scale={[-0.08, 0.08, 0.08]}>
                        <mesh
                            geometry={nodes.Object_59.geometry}
                            material={materials["Cristal.001"]}
                        />
                    </group>
                    <group
                        position={[-63.93, 18.96, -20.11]}
                        scale={[-0.08, 0.08, 0.08]}>
                        <mesh
                            geometry={nodes.Object_61.geometry}
                            material={materials.Chrome}
                        />
                        <mesh
                            geometry={nodes.Object_62.geometry}
                            material={materials.Rubber}
                        />
                    </group>
                    <group position={[-63.68, 18.52, 13.78]}>
                        <mesh
                            geometry={nodes.Object_64.geometry}
                            material={materials["Cristal.001"]}
                        />
                    </group>
                    <group
                        position={[-22.28, 21.3, 111.25]}
                        rotation={[0.08, 0, 0]}
                        scale={0.81}>
                        <mesh
                            geometry={nodes.Object_66.geometry}
                            material={materials.metal}
                        />
                        <mesh
                            geometry={nodes.Object_67.geometry}
                            material={materials.Rubber}
                        />
                    </group>
                    <group position={[-57.18, -18.83, 174.98]}>
                        <mesh
                            geometry={nodes.Object_69.geometry}
                            material={materials.Chrome}
                        />
                    </group>
                    <group position={[32.07, -32.09, -47.33]}>
                        <mesh
                            geometry={nodes.Object_71.geometry}
                            material={materials["Material.010"]}
                        />
                    </group>
                    <group
                        position={[1.01, -20.65, 2.11]}
                        rotation={[-Math.PI, 0, 0]}>
                        <mesh
                            geometry={nodes.Object_73.geometry}
                            material={materials["Material.011"]}
                        />
                    </group>
                    <group position={[0, -1.61, -100.17]}>
                        <mesh
                            geometry={nodes.Object_75.geometry}
                            material={materials.Chrome}
                        />
                    </group>
                    <group
                        position={[-60.9, 19.92, -70.54]}
                        rotation={[-0.01, 0, 0]}>
                        <mesh
                            geometry={nodes.Object_77.geometry}
                            material={materials.Chrome}
                        />
                    </group>
                    <group
                        position={[-61.84, 19.82, -70.43]}
                        rotation={[0, 0.15, 0]}>
                        <mesh
                            geometry={nodes.Object_79.geometry}
                            material={materials.Chrome}
                        />
                    </group>
                    <group
                        position={[-60.9, 19.92, -70.54]}
                        rotation={[-0.01, 0, 0]}>
                        <mesh
                            geometry={nodes.Object_81.geometry}
                            material={materials.Rubber}
                        />
                    </group>
                    <group
                        position={[-61.84, 19.82, -70.43]}
                        rotation={[0, 0.15, 0]}>
                        <mesh
                            geometry={nodes.Object_83.geometry}
                            material={materials["Chrome.003"]}
                        />
                    </group>
                    <group position={[-49.41, 1.96, -161.85]} scale={0.02}>
                        <mesh
                            geometry={nodes.Object_85.geometry}
                            material={materials.lightbulb}
                        />
                    </group>
                    <group
                        position={[-60.9, 20.2, -74.75]}
                        scale={[0.13, 0.08, 0.13]}>
                        <mesh
                            geometry={nodes.Object_87.geometry}
                            material={materials.metal}
                        />
                    </group>
                    <group
                        position={[-61.98, 20.25, -68.86]}
                        scale={[0.13, 0.08, 0.13]}>
                        <mesh
                            geometry={nodes.Object_89.geometry}
                            material={materials.metal}
                        />
                    </group>
                    <group
                        position={[-59.83, 20.25, -68.86]}
                        rotation={[Math.PI, -1.44, Math.PI]}
                        scale={[0.13, 0.08, 0.13]}>
                        <mesh
                            geometry={nodes.Object_91.geometry}
                            material={materials.metal}
                        />
                    </group>
                    <group position={[-29.18, -36.27, 151.36]} scale={1.24}>
                        <mesh
                            geometry={nodes.Object_93.geometry}
                            material={materials.Exhaust}
                        />
                    </group>
                    <group position={[-32.26, -36.43, 158.85]} scale={1.24}>
                        <mesh
                            geometry={nodes.Object_95.geometry}
                            material={materials.Exhaust}
                        />
                    </group>
                    <group position={[-25.88, -36.43, 158.85]} scale={1.24}>
                        <mesh
                            geometry={nodes.Object_97.geometry}
                            material={materials.Exhaust}
                        />
                    </group>
                    <group position={[-48.93, -9.1, -169.48]}>
                        <mesh
                            geometry={nodes.Object_99.geometry}
                            material={materials["Rubber.003"]}
                        />
                    </group>
                    <group position={[0, -17.52, -180.92]}>
                        <mesh
                            geometry={nodes.Object_101.geometry}
                            material={materials.Chrome}
                        />
                    </group>
                    <group position={[0, -17.52, -179.42]}>
                        <mesh
                            geometry={nodes.Object_103.geometry}
                            material={materials.Rubber}
                        />
                    </group>
                    <mesh
                        geometry={nodes.Object_105.geometry}
                        material={materials.Rubber}
                    />
                    <mesh
                        geometry={nodes.Object_107.geometry}
                        material={materials.Wood}
                    />
                    <mesh
                        geometry={nodes.Object_109.geometry}
                        material={materials.metal}
                    />
                    <mesh
                        geometry={nodes.Object_111.geometry}
                        material={materials.metal}
                    />
                    <mesh
                        geometry={nodes.Object_113.geometry}
                        material={materials.Rubber}
                    />
                    <mesh
                        geometry={nodes.Object_115.geometry}
                        material={materials["matte-black"]}
                    />
                    <mesh
                        geometry={nodes.Object_117.geometry}
                        material={materials["matte-black"]}
                    />
                    <mesh
                        geometry={nodes.Object_118.geometry}
                        material={materials.Cluster}
                    />
                    <group position={[-17.77, -0.13, 1.56]}>
                        <mesh
                            geometry={nodes.Object_120.geometry}
                            material={materials["matte-black"]}
                        />
                        <mesh
                            geometry={nodes.Object_121.geometry}
                            material={materials.Cluster}
                        />
                    </group>
                    <group position={[-24.48, -0.44, 2.17]}>
                        <mesh
                            geometry={nodes.Object_123.geometry}
                            material={materials["matte-black"]}
                        />
                        <mesh
                            geometry={nodes.Object_124.geometry}
                            material={materials.Cluster}
                        />
                    </group>
                    <group position={[-18.65, 0.08, 1.61]}>
                        <mesh
                            geometry={nodes.Object_126.geometry}
                            material={materials["matte-black"]}
                        />
                        <mesh
                            geometry={nodes.Object_127.geometry}
                            material={materials.Cluster}
                        />
                    </group>
                    <mesh
                        geometry={nodes.Object_129.geometry}
                        material={materials["matte-black"]}
                    />
                    <mesh
                        geometry={nodes.Object_130.geometry}
                        material={materials.Cluster}
                    />
                    <group position={[-18.65, 0.08, 1.61]}>
                        <mesh
                            geometry={nodes.Object_132.geometry}
                            material={materials["Cristal.002"]}
                        />
                    </group>
                    <mesh
                        geometry={nodes.Object_134.geometry}
                        material={materials["Cristal.002"]}
                    />
                    <group position={[-17.77, -0.13, 1.56]}>
                        <mesh
                            geometry={nodes.Object_136.geometry}
                            material={materials["Cristal.002"]}
                        />
                    </group>
                    <group position={[-27.07, 12.57, -40.74]} scale={1.28}>
                        <mesh
                            geometry={nodes.Object_138.geometry}
                            material={materials.metal}
                        />
                    </group>
                    <group position={[-69.8, 7.39, 38.82]} scale={1.21}>
                        <mesh
                            geometry={nodes.Object_140.geometry}
                            material={materials.Chrome}
                        />
                        <mesh
                            geometry={nodes.Object_141.geometry}
                            material={materials.metal}
                        />
                        <mesh
                            geometry={nodes.Object_142.geometry}
                            material={materials["matte-black"]}
                        />
                    </group>
                    <group
                        position={[-22.4, 2.12, -41.93]}
                        rotation={[-0.11, -0.02, -0.05]}>
                        <mesh
                            geometry={nodes.Object_144.geometry}
                            material={materials["matte-black"]}
                        />
                    </group>
                    <group position={[-0.59, -14.48, -64.93]}>
                        <mesh
                            geometry={nodes.Object_146.geometry}
                            material={materials["matte-black"]}
                        />
                    </group>
                    <group position={[-10.16, 53.93, -18.29]}>
                        <mesh
                            geometry={nodes.Object_148.geometry}
                            material={materials.metal}
                        />
                        <mesh
                            geometry={nodes.Object_149.geometry}
                            material={materials.Rubber}
                        />
                    </group>
                    <group position={[0.01, 51.89, -20.95]}>
                        <mesh
                            geometry={nodes.Object_151.geometry}
                            material={materials.Rubber}
                        />
                        <mesh
                            geometry={nodes.Object_152.geometry}
                            material={materials.metal}
                        />
                    </group>
                    <group
                        position={[0.01, 46.69, -20.07]}
                        rotation={[0.3, -0.25, 0.08]}>
                        <mesh
                            geometry={nodes.Object_154.geometry}
                            material={materials.Rubber}
                        />
                        <mesh
                            geometry={nodes.Object_155.geometry}
                            material={materials["Chrome.003"]}
                        />
                    </group>
                    <group position={[0, 7.22, -40.97]} rotation={[1.31, 0, 0]}>
                        <mesh
                            geometry={nodes.Object_157.geometry}
                            material={materials.metal}
                        />
                        <mesh
                            geometry={nodes.Object_158.geometry}
                            material={materials.Rubber}
                        />
                    </group>
                    <group
                        position={[-4.73, 7.26, -40.79]}
                        rotation={[1.35, 0, 0]}>
                        <mesh
                            geometry={nodes.Object_160.geometry}
                            material={materials.metal}
                        />
                        <mesh
                            geometry={nodes.Object_161.geometry}
                            material={materials.Rubber}
                        />
                    </group>
                    <group position={[-4.06, -0.48, -49.64]}>
                        <mesh
                            geometry={nodes.Object_163.geometry}
                            material={materials.Rubber}
                        />
                        <mesh
                            geometry={nodes.Object_164.geometry}
                            material={materials["Material.008"]}
                        />
                    </group>
                    <mesh
                        geometry={nodes.Object_166.geometry}
                        material={materials["matte-black"]}
                    />
                    <group position={[0, -17.66, -4.76]}>
                        <mesh
                            geometry={nodes.Object_168.geometry}
                            material={materials["matte-black"]}
                        />
                    </group>
                    <group position={[0, -16.61, -27.89]}>
                        <mesh
                            geometry={nodes.Object_170.geometry}
                            material={materials.Rubber}
                        />
                    </group>
                    <group
                        position={[-0.76, -12.1, -28.81]}
                        rotation={[-0.17, -0.16, 0.17]}
                        scale={0.01}>
                        <group position={[0, 2121.53, 0.06]} scale={131.16}>
                            <mesh
                                geometry={nodes.Object_175.geometry}
                                material={materials["matte-black"]}
                            />
                            <mesh
                                geometry={nodes.Object_176.geometry}
                                material={materials.metal}
                            />
                        </group>
                        <mesh
                            geometry={nodes.Object_172.geometry}
                            material={materials.metal}
                        />
                        <mesh
                            geometry={nodes.Object_173.geometry}
                            material={materials.Rubber}
                        />
                    </group>
                    <group
                        position={[-20.59, -24.17, -72.69]}
                        rotation={[-0.34, 0, 0]}>
                        <mesh
                            geometry={nodes.Object_178.geometry}
                            material={materials.Rubber}
                        />
                    </group>
                    <group position={[-20.48, -20.42, -74.21]}>
                        <mesh
                            geometry={nodes.Object_180.geometry}
                            material={materials.metal}
                        />
                    </group>
                    <group
                        position={[-27.78, -24.17, -72.69]}
                        rotation={[-0.34, 0, 0]}>
                        <mesh
                            geometry={nodes.Object_182.geometry}
                            material={materials.Rubber}
                        />
                    </group>
                    <group position={[-27.67, -20.42, -74.21]}>
                        <mesh
                            geometry={nodes.Object_184.geometry}
                            material={materials.metal}
                        />
                    </group>
                    <group
                        position={[-12.11, -24.25, -75.54]}
                        rotation={[-0.36, 0, 0]}>
                        <mesh
                            geometry={nodes.Object_186.geometry}
                            material={materials["metal.001"]}
                        />
                    </group>
                    <group
                        position={[-27.23, -13.29, -73.33]}
                        rotation={[-0.24, 0, 0]}>
                        <mesh
                            geometry={nodes.Object_188.geometry}
                            material={materials["matte-black"]}
                        />
                    </group>
                    <group
                        position={[-17.01, 2.52, -40.24]}
                        rotation={[1.03, 0, 0]}>
                        <mesh
                            geometry={nodes.Object_190.geometry}
                            material={materials.metal}
                        />
                        <mesh
                            geometry={nodes.Object_191.geometry}
                            material={materials["matte-black"]}
                        />
                    </group>
                    <group
                        position={[-27.48, 10.41, -27.1]}
                        rotation={[1.07, 0, 0]}>
                        <mesh
                            geometry={nodes.Object_193.geometry}
                            material={materials["Rubber.001"]}
                        />
                    </group>
                    <group
                        position={[-27.48, 13.1, -22.62]}
                        rotation={[1.03, 0, 0]}
                        scale={0.89}>
                        <mesh
                            geometry={nodes.Object_195.geometry}
                            material={materials.Wood}
                        />
                    </group>
                    <group
                        position={[-27.48, 10.41, -27.1]}
                        rotation={[1.07, 0, 0]}
                        scale={0.05}>
                        <mesh
                            geometry={nodes.Object_197.geometry}
                            material={materials["Material.007"]}
                        />
                    </group>
                    <group
                        position={[-27.48, 10.41, -27.1]}
                        rotation={[1.07, 0, 0]}
                        scale={0.05}>
                        <mesh
                            geometry={nodes.Object_199.geometry}
                            material={materials["Rubber.002"]}
                        />
                    </group>
                    <group
                        position={[-36.42, 14.14, -41.27]}
                        rotation={[-0.12, 0.04, 0.58]}>
                        <mesh
                            geometry={nodes.Object_201.geometry}
                            material={materials.material_0}
                        />
                    </group>
                    <group
                        position={[-17.5, 14.14, -42.88]}
                        rotation={[-0.13, 0.03, 0.46]}>
                        <mesh
                            geometry={nodes.Object_203.geometry}
                            material={materials.material_0}
                        />
                    </group>
                    <group
                        position={[-51.88, 12.16, -38.8]}
                        rotation={[1.58, 0.01, -0.08]}
                        scale={0.01}>
                        <mesh
                            geometry={nodes.Object_205.geometry}
                            material={materials.metal}
                        />
                        <mesh
                            geometry={nodes.Object_206.geometry}
                            material={materials["matte-black"]}
                        />
                    </group>
                    <group
                        position={[-49.04, 12.16, -39.05]}
                        rotation={[1.58, 0.01, -0.09]}
                        scale={0.01}>
                        <mesh
                            geometry={nodes.Object_208.geometry}
                            material={materials.metal}
                        />
                        <mesh
                            geometry={nodes.Object_209.geometry}
                            material={materials["matte-black"]}
                        />
                    </group>
                    <group
                        position={[-46.19, 12.16, -39.29]}
                        rotation={[1.58, 0.01, -0.09]}
                        scale={0.01}>
                        <mesh
                            geometry={nodes.Object_211.geometry}
                            material={materials.metal}
                        />
                        <mesh
                            geometry={nodes.Object_212.geometry}
                            material={materials["matte-black"]}
                        />
                    </group>
                    <group
                        position={[-43.35, 12.16, -39.54]}
                        rotation={[1.58, 0.01, -0.09]}
                        scale={0.01}>
                        <mesh
                            geometry={nodes.Object_214.geometry}
                            material={materials.metal}
                        />
                        <mesh
                            geometry={nodes.Object_215.geometry}
                            material={materials["matte-black"]}
                        />
                    </group>
                    <group
                        position={[-36.43, 14.13, -41.39]}
                        rotation={[1.48, 0.58, -0.04]}
                        scale={0}>
                        <mesh
                            geometry={nodes.Object_217.geometry}
                            material={materials["matte-black"]}
                        />
                    </group>
                    <group
                        position={[-17.51, 14.13, -42.99]}
                        rotation={[1.48, 0.58, -0.04]}
                        scale={0}>
                        <mesh
                            geometry={nodes.Object_219.geometry}
                            material={materials["matte-black"]}
                        />
                    </group>
                    <group
                        position={[-31.12, -32.97, 10.24]}
                        rotation={[0.08, 0, 0]}>
                        <mesh
                            geometry={nodes.Object_223.geometry}
                            material={materials.Seats}
                        />
                        <group position={[2.16, 0, 0]} rotation={[-0.08, 0, 0]}>
                            <mesh
                                geometry={nodes.Object_225.geometry}
                                material={materials.metal}
                            />
                        </group>
                        <group
                            position={[-13.69, 1.3, 11.48]}
                            rotation={[-0.08, 0, 0]}>
                            <mesh
                                geometry={nodes.Object_227.geometry}
                                material={materials.metal}
                            />
                        </group>
                        <mesh
                            geometry={nodes.Object_221.geometry}
                            material={materials.Seats}
                        />
                    </group>
                    <group position={[1.14, -19.08, 3.84]}>
                        <mesh
                            geometry={nodes.Object_229.geometry}
                            material={materials.Chrome}
                        />
                        <mesh
                            geometry={nodes.Object_230.geometry}
                            material={materials.Rubber}
                        />
                    </group>
                    <mesh
                        geometry={nodes.Object_232.geometry}
                        material={materials["matte-black"]}
                    />
                    <group
                        position={[-60.17, -5.07, -12.93]}
                        rotation={[0, 0, -Math.PI / 2]}>
                        <group
                            position={[3.06, 0.47, 9.18]}
                            rotation={[0, 0, Math.PI / 2]}>
                            <mesh
                                geometry={nodes.Object_237.geometry}
                                material={materials["Rubber.001"]}
                            />
                            <mesh
                                geometry={nodes.Object_238.geometry}
                                material={materials.Chrome}
                            />
                            <mesh
                                geometry={nodes.Object_239.geometry}
                                material={materials["matte-black"]}
                            />
                        </group>
                        <group
                            position={[1.95, 0.84, -12.72]}
                            rotation={[0, 0.06, Math.PI / 2]}
                            scale={1.34}>
                            <mesh
                                geometry={nodes.Object_241.geometry}
                                material={materials.metal}
                            />
                        </group>
                        <mesh
                            geometry={nodes.Object_234.geometry}
                            material={materials.Rubber}
                        />
                        <mesh
                            geometry={nodes.Object_235.geometry}
                            material={materials.Chrome}
                        />
                    </group>
                    <group
                        position={[-59.95, -7.38, -38.8]}
                        rotation={[2.75, 0, -Math.PI / 2]}
                        scale={0.02}>
                        <mesh
                            geometry={nodes.Object_243.geometry}
                            material={materials.Chrome}
                        />
                        <mesh
                            geometry={nodes.Object_244.geometry}
                            material={materials.Rubber}
                        />
                    </group>
                    <group position={[0, -1.61, -100.17]}>
                        <mesh
                            geometry={nodes.Object_246.geometry}
                            material={materials.Rubber}
                        />
                    </group>
                    <group position={[-61.47, -29.15, -98.98]}>
                        <mesh
                            geometry={nodes.Object_248.geometry}
                            material={materials.tire_side}
                        />
                        <mesh
                            geometry={nodes.Object_249.geometry}
                            material={materials.tire_tread}
                        />
                    </group>
                    <group position={[-61.47, -29.15, -98.98]}>
                        <mesh
                            geometry={nodes.Object_251.geometry}
                            material={materials.Chrome}
                        />
                    </group>
                    <group position={[-61.47, -29.15, -98.98]}>
                        <mesh
                            geometry={nodes.Object_253.geometry}
                            material={materials["metal.002"]}
                        />
                    </group>
                </group>
            </group>
        </group>
    );
}

useGLTF.preload("/fiat_850_spider/scene.gltf");
