/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: metalmorag (https://sketchfab.com/metalmorag)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/toyota-ae86-da84f6e22f20486a91b7a012556d80f6
title: Toyota AE86
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
    nodes: {
        Object_2: THREE.Mesh;
    };
    materials: {
        initialShadingGroup: THREE.MeshStandardMaterial;
    };
};

export function RaceToyota({ ...props }: JSX.IntrinsicElements["group"]) {
    const group = useRef<THREE.Group>(null);
    const { nodes, materials } = useGLTF(
        "/toyota_ae86/scene.gltf"
    ) as GLTFResult;
    return (
        <group ref={group} {...props} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
                <mesh
                    geometry={nodes.Object_2.geometry}
                    material={materials.initialShadingGroup}
                />
            </group>
        </group>
    );
}

useGLTF.preload("/toyota_ae86/scene.gltf");
