/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: MRowa (https://sketchfab.com/MRowa)
license: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
source: https://sketchfab.com/3d-models/roadsbridges-tileset-pack-558f2ea2ae7b4861b18eea228085674b
title: Roads&Bridges - Tileset pack
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    RoadX_Placeable_0: THREE.Mesh;
  };
  materials: {
    Placeable: THREE.MeshStandardMaterial;
  };
};

export default function RoadCross({
  ...props
}: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials } = useGLTF("/roadtiles/scene.gltf") as GLTFResult;
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[160, -80, 0]}>
          <mesh
            geometry={nodes.RoadX_Placeable_0.geometry}
            material={materials.Placeable}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/roadtiles/scene.gltf");
