/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: eccitatore (https://sketchfab.com/eccitatore)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/low-poly-cinema-c0fba0ff34024090b60c39028f790163
title: Low Poly Cinema
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
    nodes: {
        Object_4: THREE.Mesh;
        Object_5: THREE.Mesh;
        Object_6: THREE.Mesh;
        Object_7: THREE.Mesh;
        Object_9: THREE.Mesh;
        Object_10: THREE.Mesh;
        Object_12: THREE.Mesh;
        Object_13: THREE.Mesh;
        Object_15: THREE.Mesh;
        Object_16: THREE.Mesh;
        Object_18: THREE.Mesh;
        Object_19: THREE.Mesh;
        Object_21: THREE.Mesh;
        Object_23: THREE.Mesh;
        Object_25: THREE.Mesh;
        Object_27: THREE.Mesh;
        Object_28: THREE.Mesh;
        Object_29: THREE.Mesh;
        Object_31: THREE.Mesh;
        Object_32: THREE.Mesh;
        Object_34: THREE.Mesh;
        Object_35: THREE.Mesh;
        Object_36: THREE.Mesh;
        Object_37: THREE.Mesh;
        Object_38: THREE.Mesh;
        Object_40: THREE.Mesh;
        Object_41: THREE.Mesh;
        Object_43: THREE.Mesh;
        Object_45: THREE.Mesh;
        Object_46: THREE.Mesh;
        Object_48: THREE.Mesh;
        Object_49: THREE.Mesh;
        Object_50: THREE.Mesh;
        Object_52: THREE.Mesh;
        Object_54: THREE.Mesh;
        Object_55: THREE.Mesh;
        Object_57: THREE.Mesh;
        Object_58: THREE.Mesh;
        Object_60: THREE.Mesh;
        Object_62: THREE.Mesh;
        Object_64: THREE.Mesh;
        Object_66: THREE.Mesh;
        Object_68: THREE.Mesh;
        Object_69: THREE.Mesh;
        Object_71: THREE.Mesh;
        Object_72: THREE.Mesh;
        Object_74: THREE.Mesh;
        Object_75: THREE.Mesh;
        Object_77: THREE.Mesh;
        Object_78: THREE.Mesh;
        Object_80: THREE.Mesh;
        Object_81: THREE.Mesh;
        Object_83: THREE.Mesh;
        Object_85: THREE.Mesh;
        Object_87: THREE.Mesh;
        Object_89: THREE.Mesh;
        Object_91: THREE.Mesh;
        Object_93: THREE.Mesh;
        Object_95: THREE.Mesh;
        Object_97: THREE.Mesh;
        Object_99: THREE.Mesh;
        Object_101: THREE.Mesh;
        Object_103: THREE.Mesh;
        Object_105: THREE.Mesh;
        Object_107: THREE.Mesh;
        Object_109: THREE.Mesh;
        Object_111: THREE.Mesh;
        Object_113: THREE.Mesh;
        Object_115: THREE.Mesh;
        Object_116: THREE.Mesh;
        Object_118: THREE.Mesh;
        Object_119: THREE.Mesh;
        Object_121: THREE.Mesh;
        Object_123: THREE.Mesh;
        Object_124: THREE.Mesh;
        Object_125: THREE.Mesh;
        Object_126: THREE.Mesh;
        Object_128: THREE.Mesh;
        Object_130: THREE.Mesh;
        Object_132: THREE.Mesh;
        Object_134: THREE.Mesh;
        Object_136: THREE.Mesh;
        Object_138: THREE.Mesh;
        Object_140: THREE.Mesh;
        Object_142: THREE.Mesh;
        Object_144: THREE.Mesh;
        Object_146: THREE.Mesh;
        Object_148: THREE.Mesh;
        Object_150: THREE.Mesh;
        Object_152: THREE.Mesh;
        Object_154: THREE.Mesh;
        Object_155: THREE.Mesh;
        Object_157: THREE.Mesh;
        Object_159: THREE.Mesh;
        Object_161: THREE.Mesh;
        Object_162: THREE.Mesh;
        Object_164: THREE.Mesh;
        Object_166: THREE.Mesh;
        Object_168: THREE.Mesh;
        Object_170: THREE.Mesh;
        Object_172: THREE.Mesh;
        Object_173: THREE.Mesh;
        Object_174: THREE.Mesh;
        Object_176: THREE.Mesh;
        Object_177: THREE.Mesh;
        Object_178: THREE.Mesh;
        Object_180: THREE.Mesh;
        Object_182: THREE.Mesh;
    };
    materials: {
        taxi: THREE.MeshStandardMaterial;
        glass: THREE.MeshStandardMaterial;
        lights: THREE.MeshStandardMaterial;
        material: THREE.MeshStandardMaterial;
        black: THREE.MeshStandardMaterial;
        chrome: THREE.MeshStandardMaterial;
        light_peach: THREE.MeshStandardMaterial;
        white: THREE.MeshStandardMaterial;
        pink: THREE.MeshStandardMaterial;
        peach: THREE.MeshStandardMaterial;
        ["poster-4"]: THREE.MeshStandardMaterial;
        material_0: THREE.MeshStandardMaterial;
        ["poster-1"]: THREE.MeshStandardMaterial;
        ["poster-2"]: THREE.MeshStandardMaterial;
        cover: THREE.MeshStandardMaterial;
        material_15: THREE.MeshStandardMaterial;
        ["bg-pink"]: THREE.MeshStandardMaterial;
        zabor: THREE.MeshStandardMaterial;
        ["dark-pink"]: THREE.MeshStandardMaterial;
        flower: THREE.MeshStandardMaterial;
        grass: THREE.MeshStandardMaterial;
        blue: THREE.MeshStandardMaterial;
        yellow: THREE.MeshStandardMaterial;
        ["bg-studio"]: THREE.MeshStandardMaterial;
    };
};

export function Cinema({ ...props }: JSX.IntrinsicElements["group"]) {
    const group = useRef<THREE.Group>(null);
    const { nodes, materials } = useGLTF(
        "/low_poly_cinema/scene.gltf"
    ) as GLTFResult;
    return (
        <group ref={group} {...props} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
                <group rotation={[Math.PI / 2, 0, 0]}>
                    <group position={[-1.64, 0.41, 2.28]} scale={0.36}>
                        <mesh
                            geometry={nodes.Object_4.geometry}
                            material={materials.taxi}
                        />
                        <mesh
                            geometry={nodes.Object_5.geometry}
                            material={materials.glass}
                        />
                        <mesh
                            geometry={nodes.Object_6.geometry}
                            material={materials.lights}
                        />
                        <mesh
                            geometry={nodes.Object_7.geometry}
                            material={materials.material}
                        />
                    </group>
                    <group
                        position={[-1.38, 0.08, 2.65]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={0.08}>
                        <mesh
                            geometry={nodes.Object_9.geometry}
                            material={materials.black}
                        />
                        <mesh
                            geometry={nodes.Object_10.geometry}
                            material={materials.chrome}
                        />
                    </group>
                    <group
                        position={[-2.05, 0.08, 2.65]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={0.08}>
                        <mesh
                            geometry={nodes.Object_12.geometry}
                            material={materials.black}
                        />
                        <mesh
                            geometry={nodes.Object_13.geometry}
                            material={materials.chrome}
                        />
                    </group>
                    <group
                        position={[-1.38, 0.08, 2.02]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={0.08}>
                        <mesh
                            geometry={nodes.Object_15.geometry}
                            material={materials.black}
                        />
                        <mesh
                            geometry={nodes.Object_16.geometry}
                            material={materials.chrome}
                        />
                    </group>
                    <group
                        position={[-2.05, 0.08, 2.02]}
                        rotation={[-1.53, 0, 0]}
                        scale={0.08}>
                        <mesh
                            geometry={nodes.Object_18.geometry}
                            material={materials.black}
                        />
                        <mesh
                            geometry={nodes.Object_19.geometry}
                            material={materials.chrome}
                        />
                    </group>
                    <group
                        position={[-1.38, 0.13, 2.65]}
                        rotation={[0, -0.11, 0]}
                        scale={[0.1, 0.1, 0.02]}>
                        <mesh
                            geometry={nodes.Object_21.geometry}
                            material={materials.black}
                        />
                    </group>
                    <group
                        position={[-2.05, 0.13, 2.65]}
                        rotation={[0, -0.11, 0]}
                        scale={[0.1, 0.1, 0.02]}>
                        <mesh
                            geometry={nodes.Object_23.geometry}
                            material={materials.black}
                        />
                    </group>
                    <group
                        position={[-1.6, 0.58, 2.33]}
                        scale={[0.02, 0.04, 0.09]}>
                        <mesh
                            geometry={nodes.Object_25.geometry}
                            material={materials.lights}
                        />
                    </group>
                    <group
                        position={[2.76, 1.18, -2.17]}
                        scale={[0.54, 1.17, 1.36]}>
                        <mesh
                            geometry={nodes.Object_27.geometry}
                            material={materials.light_peach}
                        />
                        <mesh
                            geometry={nodes.Object_28.geometry}
                            material={materials.white}
                        />
                        <mesh
                            geometry={nodes.Object_29.geometry}
                            material={materials.pink}
                        />
                    </group>
                    <group
                        position={[1.91, 1.5, -2.17]}
                        scale={[0.32, 1.49, 1.61]}>
                        <mesh
                            geometry={nodes.Object_31.geometry}
                            material={materials.pink}
                        />
                        <mesh
                            geometry={nodes.Object_32.geometry}
                            material={materials.white}
                        />
                    </group>
                    <group
                        position={[0.01, 1.59, -2.17]}
                        scale={[1.58, 1.59, 1.86]}>
                        <mesh
                            geometry={nodes.Object_34.geometry}
                            material={materials.peach}
                        />
                        <mesh
                            geometry={nodes.Object_35.geometry}
                            material={materials.white}
                        />
                        <mesh
                            geometry={nodes.Object_36.geometry}
                            material={materials.pink}
                        />
                        <mesh
                            geometry={nodes.Object_37.geometry}
                            material={materials.glass}
                        />
                        <mesh
                            geometry={nodes.Object_38.geometry}
                            material={materials["poster-4"]}
                        />
                    </group>
                    <group
                        position={[-0.01, 3.49, -1.07]}
                        scale={[0.35, 1.49, 1.1]}>
                        <mesh
                            geometry={nodes.Object_40.geometry}
                            material={materials.light_peach}
                        />
                        <mesh
                            geometry={nodes.Object_41.geometry}
                            material={materials.white}
                        />
                    </group>
                    <group
                        position={[0.45, 3.25, -1.12]}
                        scale={[0.11, 1.24, 0.94]}>
                        <mesh
                            geometry={nodes.Object_43.geometry}
                            material={materials.pink}
                        />
                    </group>
                    <group
                        position={[-1.88, 1.5, -2.17]}
                        scale={[0.32, 1.49, 1.61]}>
                        <mesh
                            geometry={nodes.Object_45.geometry}
                            material={materials.pink}
                        />
                        <mesh
                            geometry={nodes.Object_46.geometry}
                            material={materials.white}
                        />
                    </group>
                    <group
                        position={[-2.73, 1.18, -2.17]}
                        scale={[0.54, 1.17, 1.36]}>
                        <mesh
                            geometry={nodes.Object_48.geometry}
                            material={materials.light_peach}
                        />
                        <mesh
                            geometry={nodes.Object_49.geometry}
                            material={materials.white}
                        />
                        <mesh
                            geometry={nodes.Object_50.geometry}
                            material={materials.pink}
                        />
                    </group>
                    <group
                        position={[-0.04, 2.21, 0.12]}
                        scale={[0.14, 0.08, 0.02]}>
                        <mesh
                            geometry={nodes.Object_52.geometry}
                            material={materials.black}
                        />
                    </group>
                    <group
                        position={[0.86, 1.73, -0.02]}
                        rotation={[1.57, 0, -0.81]}
                        scale={0.13}>
                        <mesh
                            geometry={nodes.Object_54.geometry}
                            material={materials.black}
                        />
                        <mesh
                            geometry={nodes.Object_55.geometry}
                            material={materials.white}
                        />
                    </group>
                    <group
                        position={[-0.82, 1.73, -0.01]}
                        rotation={[1.57, 0, 0.79]}
                        scale={0.13}>
                        <mesh
                            geometry={nodes.Object_57.geometry}
                            material={materials.black}
                        />
                        <mesh
                            geometry={nodes.Object_58.geometry}
                            material={materials.white}
                        />
                    </group>
                    <group
                        position={[-0.45, 3.25, -1.12]}
                        scale={[0.11, 1.24, 0.94]}>
                        <mesh
                            geometry={nodes.Object_60.geometry}
                            material={materials.pink}
                        />
                    </group>
                    <group
                        position={[1.93, 1.32, -0.59]}
                        scale={[0.05, 1.35, 0.04]}>
                        <mesh
                            geometry={nodes.Object_62.geometry}
                            material={materials.material_0}
                        />
                    </group>
                    <group
                        position={[2.09, 1.01, -0.59]}
                        scale={[0.05, 1.35, 0.04]}>
                        <mesh
                            geometry={nodes.Object_64.geometry}
                            material={materials.white}
                        />
                    </group>
                    <group
                        position={[1.77, 1.01, -0.59]}
                        scale={[0.05, 1.35, 0.04]}>
                        <mesh
                            geometry={nodes.Object_66.geometry}
                            material={materials.material_0}
                        />
                    </group>
                    <group
                        position={[0.02, 2.33, 0.1]}
                        scale={[0.54, 0.29, 0.03]}>
                        <mesh
                            geometry={nodes.Object_68.geometry}
                            material={materials.peach}
                        />
                        <mesh
                            geometry={nodes.Object_69.geometry}
                            material={materials.white}
                        />
                    </group>
                    <group
                        position={[1.08, 2.62, -0.29]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={0.3}>
                        <mesh
                            geometry={nodes.Object_71.geometry}
                            material={materials.white}
                        />
                        <mesh
                            geometry={nodes.Object_72.geometry}
                            material={materials.glass}
                        />
                    </group>
                    <group
                        position={[-1.01, 2.62, -0.29]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={0.3}>
                        <mesh
                            geometry={nodes.Object_74.geometry}
                            material={materials.white}
                        />
                        <mesh
                            geometry={nodes.Object_75.geometry}
                            material={materials.glass}
                        />
                    </group>
                    <group
                        position={[2.77, 0.88, -0.84]}
                        scale={[1.22, 1.2, 1]}>
                        <mesh
                            geometry={nodes.Object_77.geometry}
                            material={materials.black}
                        />
                        <mesh
                            geometry={nodes.Object_78.geometry}
                            material={materials["poster-1"]}
                        />
                    </group>
                    <group
                        position={[1.13, 0.87, -0.32]}
                        scale={[0.37, 0.52, 0.07]}>
                        <mesh
                            geometry={nodes.Object_80.geometry}
                            material={materials.black}
                        />
                        <mesh
                            geometry={nodes.Object_81.geometry}
                            material={materials.material_0}
                        />
                    </group>
                    <group
                        position={[0.39, 3.07, -0.21]}
                        scale={[0.03, 1.35, 0.04]}>
                        <mesh
                            geometry={nodes.Object_83.geometry}
                            material={materials.material_0}
                        />
                    </group>
                    <group
                        position={[0.5, 2.76, -0.21]}
                        scale={[0.03, 1.35, 0.04]}>
                        <mesh
                            geometry={nodes.Object_85.geometry}
                            material={materials.white}
                        />
                    </group>
                    <group
                        position={[0.54, 3.81, -1.75]}
                        rotation={[Math.PI / 2, Math.PI / 2, 0]}
                        scale={[0.03, 0.45, 0.04]}>
                        <mesh
                            geometry={nodes.Object_87.geometry}
                            material={materials.material_0}
                        />
                    </group>
                    <group
                        position={[0.54, 3.69, -1.75]}
                        rotation={[Math.PI / 2, Math.PI / 2, 0]}
                        scale={[0.03, 0.45, 0.04]}>
                        <mesh
                            geometry={nodes.Object_89.geometry}
                            material={materials.material_0}
                        />
                    </group>
                    <group
                        position={[0.54, 3.57, -1.75]}
                        rotation={[Math.PI / 2, Math.PI / 2, 0]}
                        scale={[0.03, 0.45, 0.04]}>
                        <mesh
                            geometry={nodes.Object_91.geometry}
                            material={materials.material_0}
                        />
                    </group>
                    <group
                        position={[0.54, 4.05, -1.75]}
                        rotation={[Math.PI / 2, Math.PI / 2, 0]}
                        scale={[0.03, 0.45, 0.04]}>
                        <mesh
                            geometry={nodes.Object_93.geometry}
                            material={materials.material_0}
                        />
                    </group>
                    <group
                        position={[0.54, 4.17, -1.75]}
                        rotation={[Math.PI / 2, Math.PI / 2, 0]}
                        scale={[0.03, 0.45, 0.04]}>
                        <mesh
                            geometry={nodes.Object_95.geometry}
                            material={materials.material_0}
                        />
                    </group>
                    <group
                        position={[0.54, 4.3, -1.75]}
                        rotation={[Math.PI / 2, Math.PI / 2, 0]}
                        scale={[0.03, 0.45, 0.04]}>
                        <mesh
                            geometry={nodes.Object_97.geometry}
                            material={materials.material_0}
                        />
                    </group>
                    <group
                        position={[0.54, 3.93, -1.75]}
                        rotation={[Math.PI / 2, Math.PI / 2, 0]}
                        scale={[0.03, 0.45, 0.04]}>
                        <mesh
                            geometry={nodes.Object_99.geometry}
                            material={materials.material_0}
                        />
                    </group>
                    <group position={[0.24, 2.48, 0]} scale={0.03}>
                        <mesh
                            geometry={nodes.Object_101.geometry}
                            material={materials.lights}
                        />
                    </group>
                    <group position={[-0.27, 2.48, 0]} scale={0.03}>
                        <mesh
                            geometry={nodes.Object_103.geometry}
                            material={materials.lights}
                        />
                    </group>
                    <group
                        position={[1.16, 1.62, -0.2]}
                        rotation={[0, 0, Math.PI / 2]}
                        scale={[0.02, 0.08, 0.02]}>
                        <mesh
                            geometry={nodes.Object_105.geometry}
                            material={materials.peach}
                        />
                    </group>
                    <group
                        position={[-1.13, 1.62, -0.2]}
                        rotation={[-Math.PI, 0, -Math.PI / 2]}
                        scale={[0.02, 0.08, 0.02]}>
                        <mesh
                            geometry={nodes.Object_107.geometry}
                            material={materials.peach}
                        />
                    </group>
                    <group
                        position={[-1.85, 1.32, -0.59]}
                        scale={[0.05, 1.35, 0.04]}>
                        <mesh
                            geometry={nodes.Object_109.geometry}
                            material={materials.material_0}
                        />
                    </group>
                    <group
                        position={[-1.7, 1.01, -0.59]}
                        scale={[0.05, 1.35, 0.04]}>
                        <mesh
                            geometry={nodes.Object_111.geometry}
                            material={materials.white}
                        />
                    </group>
                    <group
                        position={[-2.01, 1.01, -0.59]}
                        scale={[0.05, 1.35, 0.04]}>
                        <mesh
                            geometry={nodes.Object_113.geometry}
                            material={materials.material_0}
                        />
                    </group>
                    <group
                        position={[-2.73, 0.88, -0.84]}
                        scale={[1.19, 1.17, 0.98]}>
                        <mesh
                            geometry={nodes.Object_115.geometry}
                            material={materials.black}
                        />
                        <mesh
                            geometry={nodes.Object_116.geometry}
                            material={materials["poster-2"]}
                        />
                    </group>
                    <group
                        position={[0, 0.02, -0.34]}
                        rotation={[0, Math.PI / 2, 0]}
                        scale={[0.17, 0.19, 0.61]}>
                        <mesh
                            geometry={nodes.Object_118.geometry}
                            material={materials.white}
                        />
                        <mesh
                            geometry={nodes.Object_119.geometry}
                            material={materials.cover}
                        />
                    </group>
                    <group
                        position={[-0.01, 4.58, -0.05]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.36, 0.5, 0.39]}>
                        <mesh
                            geometry={nodes.Object_121.geometry}
                            material={materials.pink}
                        />
                    </group>
                    <group scale={[3.31, 4, 4]}>
                        <mesh
                            geometry={nodes.Object_123.geometry}
                            material={materials.material_15}
                        />
                        <mesh
                            geometry={nodes.Object_124.geometry}
                            material={materials.black}
                        />
                        <mesh
                            geometry={nodes.Object_125.geometry}
                            material={materials["bg-pink"]}
                        />
                        <mesh
                            geometry={nodes.Object_126.geometry}
                            material={materials.white}
                        />
                    </group>
                    <group
                        position={[1.09, 0.01, 2.99]}
                        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                        scale={[0.05, 0.19, 0.01]}>
                        <mesh
                            geometry={nodes.Object_128.geometry}
                            material={materials.material_0}
                        />
                    </group>
                    <group
                        position={[0.01, 0.01, 2.22]}
                        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                        scale={[0.11, 0.57, 0.01]}>
                        <mesh
                            geometry={nodes.Object_130.geometry}
                            material={materials.material_0}
                        />
                    </group>
                    <group
                        position={[-2.78, 0.01, 2.99]}
                        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                        scale={[0.05, 0.19, 0.01]}>
                        <mesh
                            geometry={nodes.Object_132.geometry}
                            material={materials.material_0}
                        />
                    </group>
                    <group
                        position={[0.81, 0.16, 1.78]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.19, 0.27, 0.13]}>
                        <mesh
                            geometry={nodes.Object_134.geometry}
                            material={materials.zabor}
                        />
                    </group>
                    <group
                        position={[2.82, 0.16, 1.78]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.19, 0.27, 0.13]}>
                        <mesh
                            geometry={nodes.Object_136.geometry}
                            material={materials.zabor}
                        />
                    </group>
                    <group
                        position={[2.32, 0.16, 1.78]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.19, 0.27, 0.13]}>
                        <mesh
                            geometry={nodes.Object_138.geometry}
                            material={materials.zabor}
                        />
                    </group>
                    <group
                        position={[1.32, 0.16, 1.78]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.19, 0.27, 0.13]}>
                        <mesh
                            geometry={nodes.Object_140.geometry}
                            material={materials.zabor}
                        />
                    </group>
                    <group
                        position={[1.82, 0.16, 1.78]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.19, 0.27, 0.13]}>
                        <mesh
                            geometry={nodes.Object_142.geometry}
                            material={materials.zabor}
                        />
                    </group>
                    <group
                        position={[-3.03, 0.16, 1.78]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.19, 0.27, 0.13]}>
                        <mesh
                            geometry={nodes.Object_144.geometry}
                            material={materials.zabor}
                        />
                    </group>
                    <group
                        position={[-1.02, 0.16, 1.78]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.19, 0.27, 0.13]}>
                        <mesh
                            geometry={nodes.Object_146.geometry}
                            material={materials.zabor}
                        />
                    </group>
                    <group
                        position={[-1.52, 0.16, 1.78]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.19, 0.27, 0.13]}>
                        <mesh
                            geometry={nodes.Object_148.geometry}
                            material={materials.zabor}
                        />
                    </group>
                    <group
                        position={[-2.52, 0.16, 1.78]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.19, 0.27, 0.13]}>
                        <mesh
                            geometry={nodes.Object_150.geometry}
                            material={materials.zabor}
                        />
                    </group>
                    <group
                        position={[-2.02, 0.16, 1.78]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[0.19, 0.27, 0.13]}>
                        <mesh
                            geometry={nodes.Object_152.geometry}
                            material={materials.zabor}
                        />
                    </group>
                    <group
                        position={[0.9, 0.57, 1.48]}
                        scale={[0.03, 0.42, 0.03]}>
                        <mesh
                            geometry={nodes.Object_154.geometry}
                            material={materials.black}
                        />
                        <mesh
                            geometry={nodes.Object_155.geometry}
                            material={materials.lights}
                        />
                    </group>
                    <group
                        position={[3.14, 0.99, 1.02]}
                        rotation={[0, -0.59, 0]}
                        scale={[0.03, 1.1, 0.03]}>
                        <mesh
                            geometry={nodes.Object_157.geometry}
                            material={materials["dark-pink"]}
                        />
                    </group>
                    <group
                        position={[-3.15, 0.99, 1.09]}
                        rotation={[0, 0.79, 0]}
                        scale={[0.03, 1.1, 0.03]}>
                        <mesh
                            geometry={nodes.Object_159.geometry}
                            material={materials["dark-pink"]}
                        />
                    </group>
                    <group
                        position={[-0.68, 0.57, 1.46]}
                        scale={[0.03, 0.42, 0.03]}>
                        <mesh
                            geometry={nodes.Object_161.geometry}
                            material={materials.black}
                        />
                        <mesh
                            geometry={nodes.Object_162.geometry}
                            material={materials.lights}
                        />
                    </group>
                    <group
                        position={[1.1, 0.09, -0.15]}
                        scale={[0.46, 0.09, 0.09]}>
                        <mesh
                            geometry={nodes.Object_164.geometry}
                            material={materials.flower}
                        />
                    </group>
                    <group
                        position={[-2.74, 0.09, -0.64]}
                        scale={[0.46, 0.09, 0.09]}>
                        <mesh
                            geometry={nodes.Object_166.geometry}
                            material={materials.flower}
                        />
                    </group>
                    <group
                        position={[1.09, 0.05, -0.16]}
                        scale={[0.44, 0.28, 0.09]}>
                        <mesh
                            geometry={nodes.Object_168.geometry}
                            material={materials.grass}
                        />
                    </group>
                    <group
                        position={[-2.75, 0.05, -0.65]}
                        scale={[0.44, 0.28, 0.09]}>
                        <mesh
                            geometry={nodes.Object_170.geometry}
                            material={materials.grass}
                        />
                    </group>
                    <group
                        position={[2.71, 0.2, 1.55]}
                        scale={[0.08, 0.16, 0.1]}>
                        <mesh
                            geometry={nodes.Object_172.geometry}
                            material={materials.chrome}
                        />
                        <mesh
                            geometry={nodes.Object_173.geometry}
                            material={materials.black}
                        />
                        <mesh
                            geometry={nodes.Object_174.geometry}
                            material={materials.blue}
                        />
                    </group>
                    <group
                        position={[2.9, 0.2, 1.58]}
                        rotation={[0, -0.07, 0]}
                        scale={[0.08, 0.16, 0.1]}>
                        <mesh
                            geometry={nodes.Object_176.geometry}
                            material={materials.chrome}
                        />
                        <mesh
                            geometry={nodes.Object_177.geometry}
                            material={materials.black}
                        />
                        <mesh
                            geometry={nodes.Object_178.geometry}
                            material={materials.yellow}
                        />
                    </group>
                    <group
                        position={[0, 0.28, -0.34]}
                        rotation={[Math.PI / 2, 0, -1.58]}
                        scale={[0.16, 0.22, 0.11]}>
                        <mesh
                            geometry={nodes.Object_180.geometry}
                            material={materials.white}
                        />
                    </group>
                </group>
            </group>
        </group>
    );
}

useGLTF.preload("/low_poly_cinema/scene.gltf");
