/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: ElectroNick (https://sketchfab.com/ElectroNick)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/palm-trees-20f8a8d5054b4191afb7cf3270dbd586
title: Palm Trees
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Palm_tree_002_v2_M_palm_bark_011_0: THREE.Mesh;
    Palm_tree_002_v2_M_frond_03_inst_Inst1_0: THREE.Mesh;
    Palm_tree_002_v2_M_palm_bark_021_0: THREE.Mesh;
    Palm_tree_002_v2_M_frond_01_inst1_0: THREE.Mesh;
    Palm_tree_002_v2_M_bark_hair_inst1_0: THREE.Mesh;
  };
  materials: {
    ["M_palm_bark_01.1"]: THREE.MeshStandardMaterial;
    M_frond_03_inst_Inst1: THREE.MeshStandardMaterial;
    ["M_palm_bark_02.1"]: THREE.MeshStandardMaterial;
    ["M_frond_01_inst.1"]: THREE.MeshStandardMaterial;
    ["M_bark_hair_inst.1"]: THREE.MeshStandardMaterial;
  };
};

export default function PalmTree1({
  ...props
}: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials } = useGLTF("/palm_trees/scene.gltf") as GLTFResult;
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Palm_tree_002_v2_M_palm_bark_011_0.geometry}
          material={materials["M_palm_bark_01.1"]}
        />
        <mesh
          geometry={nodes.Palm_tree_002_v2_M_frond_03_inst_Inst1_0.geometry}
          material={materials.M_frond_03_inst_Inst1}
        />
        <mesh
          geometry={nodes.Palm_tree_002_v2_M_palm_bark_021_0.geometry}
          material={materials["M_palm_bark_02.1"]}
        />
        <mesh
          geometry={nodes.Palm_tree_002_v2_M_frond_01_inst1_0.geometry}
          material={materials["M_frond_01_inst.1"]}
        />
        <mesh
          geometry={nodes.Palm_tree_002_v2_M_bark_hair_inst1_0.geometry}
          material={materials["M_bark_hair_inst.1"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/palm_trees/scene.gltf");
