/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: SPLEEN VISION (https://sketchfab.com/spleen.vision)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/pavement-in-the-park-a953218836004ffdb4004bfb65d33c98
title: pavement in the park
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh;
    Object_3: THREE.Mesh;
    Object_4: THREE.Mesh;
  };
  materials: {
    textured_0: THREE.MeshBasicMaterial;
  };
};

export default function ParkPavement({
  ...props
}: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials } = useGLTF(
    "/pavement_in_the_park/scene.gltf"
  ) as GLTFResult;
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.69}>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials.textured_0}
        />
        <mesh
          geometry={nodes.Object_3.geometry}
          material={materials.textured_0}
        />
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials.textured_0}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/pavement_in_the_park/scene.gltf");
