/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: ditovirnantio (https://sketchfab.com/ditovirnantio)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/toyota-corolla-e70-1980-c4d66d21968c41da89114e2300578bc5
title: Toyota corolla e70 (1980)
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
    nodes: {
        ["base001_Material_#83_0"]: THREE.Mesh;
        NGon001_Acrylic_Opaque_Black_0: THREE.Mesh;
        NGon001_Glass_Clear_0: THREE.Mesh;
        NGon001_Aluminium_Brushed_Distorted_0: THREE.Mesh;
        ["Plane006_Material_#57_0"]: THREE.Mesh;
        Plane007__0: THREE.Mesh;
        Object001_Aluminium_Brushed_Distorted_0: THREE.Mesh;
        Box004_Acrylic_Opaque_Black_0: THREE.Mesh;
        toy_corolladx_95_undercarriagea_undercarriage_001_Acrylic_Opaque_Black_0: THREE.Mesh;
        toy_corolladx_95_mirrorR_plastic2_001_Aluminium_Brushed_Distorted_0: THREE.Mesh;
        toy_corolladx_95_mirrorR_plastic2__Aluminium_Brushed_Distorted_0: THREE.Mesh;
        ["toy_corolladx_95_mirrorR_chrome_001_Material_#55_0"]: THREE.Mesh;
        toy_corolladx_95_seatL_interior_001_Acrylic_Opaque_Black_0: THREE.Mesh;
        toy_corolladx_95_steering_wheel_interior_001_Acrylic_Opaque_Black_0: THREE.Mesh;
        toy_corolladx_95_seatR_interior_001_Acrylic_Opaque_Black_0: THREE.Mesh;
        toy_corolladx_95_interior_interior_001_Acrylic_Opaque_Black_0: THREE.Mesh;
        ["toy_corolladx_95_mirrorR_chrome__Material_#55_0"]: THREE.Mesh;
        toy_corolladx_95_body_plastic2_001_Acrylic_Opaque_Black_0: THREE.Mesh;
        ["Object_Material_#53_0"]: THREE.Mesh;
        Object002_Acrylic_Opaque_Black_0: THREE.Mesh;
        ["Plane008_Material_#54_0"]: THREE.Mesh;
        ["Object006_Material_#56_0"]: THREE.Mesh;
        ["Object007_Material_#54_0"]: THREE.Mesh;
        Plane009__0: THREE.Mesh;
        ["Plane010_Material_#57_0"]: THREE.Mesh;
        Box043_Aluminium_Brushed_Distorted_0: THREE.Mesh;
        ["Plane011_Material_#57_0"]: THREE.Mesh;
        ["Plane012_Material_#57_0"]: THREE.Mesh;
        Object009_Aluminium_Brushed_Distorted_0: THREE.Mesh;
        Object011_Aluminium_Brushed_Distorted_0: THREE.Mesh;
        ["Box044_Material_#54_0"]: THREE.Mesh;
        ["Box045_Material_#54_0"]: THREE.Mesh;
        ["Plane013_Material_#53_0"]: THREE.Mesh;
        ["Object016_Material_#53_0"]: THREE.Mesh;
    };
    materials: {
        Material_83: THREE.MeshStandardMaterial;
        Acrylic_Opaque_Black: THREE.MeshStandardMaterial;
        Glass_Clear: THREE.MeshStandardMaterial;
        Aluminium_Brushed_Distorted: THREE.MeshStandardMaterial;
        Material_57: THREE.MeshStandardMaterial;
        Plane007__0: THREE.MeshStandardMaterial;
        Material_55: THREE.MeshStandardMaterial;
        Material_53: THREE.MeshStandardMaterial;
        Material_54: THREE.MeshStandardMaterial;
        Material_56: THREE.MeshStandardMaterial;
    };
};

export default function Toyota({ ...props }: JSX.IntrinsicElements["group"]) {
    const group = useRef<THREE.Group>(null);
    const { nodes, materials } = useGLTF(
        "/toyota_corolla_e70_1980/scene.gltf"
    ) as GLTFResult;
    return (
        <group ref={group} {...props} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
                <group rotation={[Math.PI / 2, 0, 0]}>
                    <group
                        position={[37.83, 38.14, -107.97]}
                        rotation={[0, -Math.PI / 2, 0]}
                        scale={3.33}>
                        <mesh
                            geometry={nodes["base001_Material_#83_0"].geometry}
                            material={materials.Material_83}
                        />
                    </group>
                    <group
                        position={[118.04, 71.13, -167.38]}
                        rotation={[0, 0, Math.PI / 2]}
                        scale={[2.68, 1.04, 3.33]}>
                        <group position={[0.01, 35.71, -1.88]}>
                            <mesh
                                geometry={
                                    nodes.NGon001_Acrylic_Opaque_Black_0
                                        .geometry
                                }
                                material={materials.Acrylic_Opaque_Black}
                            />
                            <mesh
                                geometry={nodes.NGon001_Glass_Clear_0.geometry}
                                material={materials.Glass_Clear}
                            />
                            <mesh
                                geometry={
                                    nodes.NGon001_Aluminium_Brushed_Distorted_0
                                        .geometry
                                }
                                material={materials.Aluminium_Brushed_Distorted}
                            />
                        </group>
                    </group>
                    <group
                        position={[64.16, 55.27, -175.16]}
                        rotation={[Math.PI, 0, -Math.PI]}
                        scale={3.33}>
                        <mesh
                            geometry={nodes["Plane006_Material_#57_0"].geometry}
                            material={materials.Material_57}
                        />
                    </group>
                    <group
                        position={[47.08, 36.71, -108.16]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[-2.02, 2.49, 2.49]}>
                        <group position={[0.69, 0, 12.56]}>
                            <mesh
                                geometry={nodes.Plane007__0.geometry}
                                material={materials.Plane007__0}
                            />
                        </group>
                    </group>
                    <group
                        position={[53.87, 36.71, -108.16]}
                        rotation={[-0.06, Math.PI / 2, 0]}
                        scale={[-1.73, 1.73, 1.78]}>
                        <mesh
                            geometry={
                                nodes.Object001_Aluminium_Brushed_Distorted_0
                                    .geometry
                            }
                            material={materials.Aluminium_Brushed_Distorted}
                        />
                    </group>
                    <group
                        position={[55.19, 29.66, 11.91]}
                        rotation={[0, -Math.PI / 2, 0]}
                        scale={2.54}>
                        <mesh
                            geometry={
                                nodes.Box004_Acrylic_Opaque_Black_0.geometry
                            }
                            material={materials.Acrylic_Opaque_Black}
                        />
                    </group>
                    <group
                        position={[118.05, 76.5, 24.85]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={2.54}>
                        <group
                            position={[0.43, 1.56, -16.36]}
                            rotation={[Math.PI / 2, 0, 0]}
                            scale={[1.15, 1, 0.96]}>
                            <mesh
                                geometry={
                                    nodes
                                        .toy_corolladx_95_undercarriagea_undercarriage_001_Acrylic_Opaque_Black_0
                                        .geometry
                                }
                                material={materials.Acrylic_Opaque_Black}
                            />
                        </group>
                        <group
                            position={[0.15, -3.57, -18.73]}
                            rotation={[Math.PI / 2, 0, 0]}
                            scale={[-1, 1, 1]}>
                            <mesh
                                geometry={
                                    nodes
                                        .toy_corolladx_95_mirrorR_plastic2_001_Aluminium_Brushed_Distorted_0
                                        .geometry
                                }
                                material={materials.Aluminium_Brushed_Distorted}
                            />
                        </group>
                        <group
                            position={[-0.15, -1.07, -19.79]}
                            rotation={[Math.PI / 2, 0, 0]}>
                            <mesh
                                geometry={
                                    nodes
                                        .toy_corolladx_95_mirrorR_plastic2__Aluminium_Brushed_Distorted_0
                                        .geometry
                                }
                                material={materials.Aluminium_Brushed_Distorted}
                            />
                        </group>
                        <group
                            position={[0.15, -3.57, -18.73]}
                            rotation={[Math.PI / 2, 0, 0]}
                            scale={[-1, 1, 1]}>
                            <mesh
                                geometry={
                                    nodes[
                                        "toy_corolladx_95_mirrorR_chrome_001_Material_#55_0"
                                    ].geometry
                                }
                                material={materials.Material_55}
                            />
                        </group>
                        <group
                            position={[0.23, -3.03, -19.17]}
                            rotation={[Math.PI / 2, 0, 0]}
                            scale={[1.05, 1, 1]}>
                            <mesh
                                geometry={
                                    nodes
                                        .toy_corolladx_95_seatL_interior_001_Acrylic_Opaque_Black_0
                                        .geometry
                                }
                                material={materials.Acrylic_Opaque_Black}
                            />
                        </group>
                        <group
                            position={[0.23, -3.03, -19.17]}
                            rotation={[Math.PI / 2, 0, 0]}
                            scale={[1.05, 1, 1]}>
                            <mesh
                                geometry={
                                    nodes
                                        .toy_corolladx_95_steering_wheel_interior_001_Acrylic_Opaque_Black_0
                                        .geometry
                                }
                                material={materials.Acrylic_Opaque_Black}
                            />
                        </group>
                        <group
                            position={[0.23, -3.03, -19.17]}
                            rotation={[Math.PI / 2, 0, 0]}
                            scale={[1.05, 1, 1]}>
                            <mesh
                                geometry={
                                    nodes
                                        .toy_corolladx_95_seatR_interior_001_Acrylic_Opaque_Black_0
                                        .geometry
                                }
                                material={materials.Acrylic_Opaque_Black}
                            />
                        </group>
                        <group
                            position={[0.23, -3.69, -19.17]}
                            rotation={[Math.PI / 2, 0, 0]}
                            scale={[1.05, 1, 0.9]}>
                            <mesh
                                geometry={
                                    nodes
                                        .toy_corolladx_95_interior_interior_001_Acrylic_Opaque_Black_0
                                        .geometry
                                }
                                material={materials.Acrylic_Opaque_Black}
                            />
                        </group>
                        <group
                            position={[-0.15, -1.07, -19.79]}
                            rotation={[Math.PI / 2, 0, 0]}>
                            <mesh
                                geometry={
                                    nodes[
                                        "toy_corolladx_95_mirrorR_chrome__Material_#55_0"
                                    ].geometry
                                }
                                material={materials.Material_55}
                            />
                        </group>
                    </group>
                    <group position={[118.44, 31.36, 51.11]} scale={2.54}>
                        <mesh
                            geometry={
                                nodes
                                    .toy_corolladx_95_body_plastic2_001_Acrylic_Opaque_Black_0
                                    .geometry
                            }
                            material={materials.Acrylic_Opaque_Black}
                        />
                    </group>
                    <group
                        position={[79.6, 116.99, -26.95]}
                        rotation={[0, -Math.PI / 2, 0]}
                        scale={3.33}>
                        <group position={[-24.34, -23.69, 12.55]}>
                            <mesh
                                geometry={
                                    nodes["Object_Material_#53_0"].geometry
                                }
                                material={materials.Material_53}
                            />
                        </group>
                    </group>
                    <group
                        position={[42.05, 101.01, -34.13]}
                        scale={[1.82, 2.54, 2.54]}>
                        <group position={[29.96, -28.24, 26.85]}>
                            <mesh
                                geometry={
                                    nodes.Object002_Acrylic_Opaque_Black_0
                                        .geometry
                                }
                                material={materials.Acrylic_Opaque_Black}
                            />
                        </group>
                    </group>
                    <group
                        position={[65.39, 71.14, -173.28]}
                        rotation={[Math.PI, 0, -Math.PI]}
                        scale={2.54}>
                        <mesh
                            geometry={nodes["Plane008_Material_#54_0"].geometry}
                            material={materials.Material_54}
                        />
                    </group>
                    <group
                        position={[37.83, 38.14, -107.97]}
                        rotation={[0, -Math.PI / 2, 0]}
                        scale={3.33}>
                        <mesh
                            geometry={
                                nodes["Object006_Material_#56_0"].geometry
                            }
                            material={materials.Material_56}
                        />
                    </group>
                    <group
                        position={[118.04, 71.13, -167.38]}
                        rotation={[0, 0, Math.PI / 2]}
                        scale={[2.68, 1.04, 3.33]}>
                        <group position={[0.01, 35.71, -1.88]}>
                            <mesh
                                geometry={
                                    nodes["Object007_Material_#54_0"].geometry
                                }
                                material={materials.Material_54}
                            />
                        </group>
                    </group>
                    <group
                        position={[33.08, 51.92, 225.43]}
                        rotation={[Math.PI, -Math.PI / 2, 0]}
                        scale={[4.9, 3.33, 3.64]}>
                        <mesh
                            geometry={nodes.Plane009__0.geometry}
                            material={materials.Plane007__0}
                        />
                    </group>
                    <group
                        position={[59.07, 50.38, 234.19]}
                        rotation={[0, 0, Math.PI]}
                        scale={[3.64, 3.33, 4.9]}>
                        <mesh
                            geometry={nodes["Plane010_Material_#57_0"].geometry}
                            material={materials.Material_57}
                        />
                    </group>
                    <group
                        position={[118.13, 51.87, 234.33]}
                        rotation={[0, 0, Math.PI]}
                        scale={[3.64, 3.33, 4.9]}>
                        <mesh
                            geometry={
                                nodes.Box043_Aluminium_Brushed_Distorted_0
                                    .geometry
                            }
                            material={materials.Aluminium_Brushed_Distorted}
                        />
                    </group>
                    <group
                        position={[39.82, 69.97, -145.83]}
                        rotation={[Math.PI, -1.48, Math.PI]}
                        scale={1.8}>
                        <mesh
                            geometry={nodes["Plane011_Material_#57_0"].geometry}
                            material={materials.Material_57}
                        />
                    </group>
                    <group
                        position={[196.28, 69.97, -145.83]}
                        rotation={[Math.PI, 1.48, -Math.PI]}
                        scale={[-1.8, 1.8, 1.8]}>
                        <mesh
                            geometry={nodes["Plane012_Material_#57_0"].geometry}
                            material={materials.Material_57}
                        />
                    </group>
                    <group
                        position={[37.83, 38.14, -107.97]}
                        rotation={[0, -Math.PI / 2, 0]}
                        scale={3.33}>
                        <mesh
                            geometry={
                                nodes.Object009_Aluminium_Brushed_Distorted_0
                                    .geometry
                            }
                            material={materials.Aluminium_Brushed_Distorted}
                        />
                    </group>
                    <group
                        position={[38.26, 79.13, 73.93]}
                        rotation={[0, -Math.PI / 2, 0]}
                        scale={3.33}>
                        <group position={[-54.65, -12.31, 0.03]}>
                            <mesh
                                geometry={
                                    nodes
                                        .Object011_Aluminium_Brushed_Distorted_0
                                        .geometry
                                }
                                material={materials.Aluminium_Brushed_Distorted}
                            />
                        </group>
                    </group>
                    <group position={[63.35, 76.1, 218.39]} scale={2.54}>
                        <mesh
                            geometry={nodes["Box044_Material_#54_0"].geometry}
                            material={materials.Material_54}
                        />
                    </group>
                    <group position={[174.85, 76.1, 218.39]} scale={2.54}>
                        <mesh
                            geometry={nodes["Box045_Material_#54_0"].geometry}
                            material={materials.Material_54}
                        />
                    </group>
                    <group
                        position={[44.01, 113.42, 43.43]}
                        rotation={[0, -Math.PI / 2, 0]}
                        scale={2.54}>
                        <mesh
                            geometry={nodes["Plane013_Material_#53_0"].geometry}
                            material={materials.Material_53}
                        />
                    </group>
                    <group
                        position={[79.6, 116.99, 137.27]}
                        rotation={[0, -Math.PI / 2, 0]}
                        scale={[-3.33, 3.33, 3.33]}>
                        <group position={[-24.34, -23.69, 12.55]}>
                            <mesh
                                geometry={
                                    nodes["Object016_Material_#53_0"].geometry
                                }
                                material={materials.Material_53}
                            />
                        </group>
                    </group>
                </group>
            </group>
        </group>
    );
}

useGLTF.preload("/toyota_corolla_e70_1980/scene.gltf");
