/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Shaddy (https://sketchfab.com/Shaddy)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/the-old-fountain-dd7909ffc4a84a45b3111030c51e43c6
title: The Old Fountain
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    well_groundPlate_low_bricks_borderStone_M_0: THREE.Mesh;
    well_groundPlate_low_bricks_m_0: THREE.Mesh;
    well_base_bottom_low_well_base_bottom_M_0: THREE.Mesh;
    well_base_top_low_well_base_top1_0: THREE.Mesh;
    middlePart_bottom_low_middlePart_bottom_M_0: THREE.Mesh;
    middlePart_middle_low_top_M_0: THREE.Mesh;
    middlePart_top_low_top_M_0: THREE.Mesh;
    deko_middle_low_top_M_0: THREE.Mesh;
    _low_top_M_0: THREE.Mesh;
    _low_top_M_0_1: THREE.Mesh;
    _low_top_M_0_2: THREE.Mesh;
    _low_top_M_0_3: THREE.Mesh;
    _low_top_M_0_4: THREE.Mesh;
    _low_top_M_0_5: THREE.Mesh;
    _low_top_M_0_6: THREE.Mesh;
    _low_top_M_0_7: THREE.Mesh;
    well_building_low_bricks_m_0: THREE.Mesh;
    well_building_low_bricks_borderStone_M_0: THREE.Mesh;
    well_doorway_low_well_doorway_M_0: THREE.Mesh;
    well_step_low_well_doorway_M_0: THREE.Mesh;
    well_door_low1_well_metalDoor_M_0: THREE.Mesh;
    well_door_low2_well_metalDoor_M_0: THREE.Mesh;
  };
  materials: {
    bricks_borderStone_M: THREE.MeshStandardMaterial;
    bricks_m: THREE.MeshStandardMaterial;
    well_base_bottom_M: THREE.MeshStandardMaterial;
    well_base_top1: THREE.MeshStandardMaterial;
    middlePart_bottom_M: THREE.MeshStandardMaterial;
    top_M: THREE.MeshStandardMaterial;
    well_doorway_M: THREE.MeshStandardMaterial;
    well_metalDoor_M: THREE.MeshStandardMaterial;
  };
};

export default function WaterFountain({
  ...props
}: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials } = useGLTF(
    "/the_old_fountain/scene.gltf"
  ) as GLTFResult;
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={
              nodes.well_groundPlate_low_bricks_borderStone_M_0.geometry
            }
            material={materials.bricks_borderStone_M}
          />
          <mesh
            geometry={nodes.well_groundPlate_low_bricks_m_0.geometry}
            material={materials.bricks_m}
          />
          <mesh
            geometry={nodes.well_base_bottom_low_well_base_bottom_M_0.geometry}
            material={materials.well_base_bottom_M}
          />
          <mesh
            geometry={nodes.well_base_top_low_well_base_top1_0.geometry}
            material={materials.well_base_top1}
          />
          <mesh
            geometry={
              nodes.middlePart_bottom_low_middlePart_bottom_M_0.geometry
            }
            material={materials.middlePart_bottom_M}
          />
          <mesh
            geometry={nodes.middlePart_middle_low_top_M_0.geometry}
            material={materials.top_M}
          />
          <mesh
            geometry={nodes.middlePart_top_low_top_M_0.geometry}
            material={materials.top_M}
          />
          <mesh
            geometry={nodes.deko_middle_low_top_M_0.geometry}
            material={materials.top_M}
          />
          <mesh
            geometry={nodes._low_top_M_0.geometry}
            material={materials.top_M}
          />
          <mesh
            geometry={nodes._low_top_M_0_1.geometry}
            material={materials.top_M}
          />
          <mesh
            geometry={nodes._low_top_M_0_2.geometry}
            material={materials.top_M}
          />
          <mesh
            geometry={nodes._low_top_M_0_3.geometry}
            material={materials.top_M}
          />
          <mesh
            geometry={nodes._low_top_M_0_4.geometry}
            material={materials.top_M}
          />
          <mesh
            geometry={nodes._low_top_M_0_5.geometry}
            material={materials.top_M}
          />
          <mesh
            geometry={nodes._low_top_M_0_6.geometry}
            material={materials.top_M}
          />
          <mesh
            geometry={nodes._low_top_M_0_7.geometry}
            material={materials.top_M}
          />
          <mesh
            geometry={nodes.well_building_low_bricks_m_0.geometry}
            material={materials.bricks_m}
          />
          <mesh
            geometry={nodes.well_building_low_bricks_borderStone_M_0.geometry}
            material={materials.bricks_borderStone_M}
          />
          <mesh
            geometry={nodes.well_doorway_low_well_doorway_M_0.geometry}
            material={materials.well_doorway_M}
          />
          <mesh
            geometry={nodes.well_step_low_well_doorway_M_0.geometry}
            material={materials.well_doorway_M}
          />
          <group position={[0.5, 0, 0]}>
            <mesh
              geometry={nodes.well_door_low1_well_metalDoor_M_0.geometry}
              material={materials.well_metalDoor_M}
            />
          </group>
          <group position={[-0.5, 0, 0]}>
            <mesh
              geometry={nodes.well_door_low2_well_metalDoor_M_0.geometry}
              material={materials.well_metalDoor_M}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/the_old_fountain/scene.gltf");
